import type { ScreenDefinition } from '@/types/screens';

/**
 * The single source of truth for every TBOS screen — mirrors
 * tbos-blueprint/04_SCREEN_INVENTORY.md 1:1, using its official screen IDs.
 * app/router builds every <Route> from this array; RailNav/MobileTabBar/
 * Breadcrumb read it instead of hardcoding paths. validateRegistry.ts enforces
 * uniqueness and that every `permission` key exists in permissionRegistry.ts.
 */
export const SCREEN_REGISTRY: ScreenDefinition[] = [
  // ---- Orientation layer ----
  {
    id: 'HOME-01',
    name: 'Home',
    path: '/home',
    moduleId: 'home',
    permission: 'home.view',
    navGroup: 'orientation',
    hasNavEntry: true,
    status: 'placeholder',
    purpose: 'Account-level front door; answers "how is my business doing" at a glance.',
  },
  {
    id: 'TODAY-01',
    name: 'Today',
    path: '/today',
    moduleId: 'today',
    permission: 'today.view',
    navGroup: 'orientation',
    hasNavEntry: true,
    status: 'ready',
    purpose: 'Prioritized, cross-module, continuously-refreshed worklist — the Decision Support System surface.',
  },
  {
    id: 'TASK-01',
    name: 'Tasks List',
    path: '/tasks',
    moduleId: 'tasks',
    permission: 'tasks.view',
    navGroup: 'orientation',
    hasNavEntry: true,
    status: 'placeholder',
    purpose: 'Durable, assignable, checkable worklist — distinct from Today’s algorithmic ranking.',
  },
  {
    id: 'TASK-02',
    name: 'Task Detail',
    path: '/tasks/:taskId',
    moduleId: 'tasks',
    permission: 'tasks.view',
    navGroup: 'orientation',
    hasNavEntry: false,
    status: 'placeholder',
    purpose: 'View/edit a single task without leaving the calling context.',
  },

  // ---- Operating layer ----
  {
    id: 'PROP-01',
    name: 'Properties List',
    path: '/properties',
    moduleId: 'properties',
    permission: 'properties.view',
    navGroup: 'operating',
    hasNavEntry: true,
    status: 'ready',
    purpose: 'Browse/filter/search the broker’s or agency’s property inventory.',
  },
  {
    id: 'PROP-02',
    name: 'Property Detail',
    path: '/properties/:propertyId',
    moduleId: 'properties',
    permission: 'properties.view',
    navGroup: 'operating',
    hasNavEntry: false,
    status: 'ready',
    purpose: 'Single source of truth for one property across its full lifecycle.',
  },
  {
    id: 'PROP-03',
    name: 'Create/Edit Property',
    path: '/properties/new',
    moduleId: 'properties',
    permission: 'properties.create',
    navGroup: 'operating',
    hasNavEntry: false,
    status: 'ready',
    purpose: 'Guided, front-loaded creation/edit wizard (WF-PROPERTY-NEW).',
  },
  {
    id: 'PROJ-01',
    name: 'Projects List',
    path: '/projects',
    moduleId: 'projects',
    permission: 'projects.view',
    navGroup: 'operating',
    hasNavEntry: true,
    status: 'ready',
    purpose: 'Browse/filter developer/multi-unit inventory.',
  },
  {
    id: 'PROJ-02',
    name: 'Project Detail',
    path: '/projects/:projectId',
    moduleId: 'projects',
    permission: 'projects.view',
    navGroup: 'operating',
    hasNavEntry: false,
    status: 'ready',
    purpose: 'Single source of truth for a project and its units.',
  },
  {
    id: 'PROJ-03',
    name: 'Create/Edit Project',
    path: '/projects/new',
    moduleId: 'projects',
    permission: 'projects.create',
    navGroup: 'operating',
    hasNavEntry: false,
    status: 'ready',
    purpose: 'Guided creation flow, project-plus-units.',
  },
  {
    id: 'LEAD-01',
    name: 'Leads Pipeline',
    path: '/leads',
    moduleId: 'leads',
    permission: 'leads.view',
    navGroup: 'operating',
    hasNavEntry: true,
    status: 'ready',
    purpose: 'The Unified Lead Pipeline — kanban-style stage view of every lead.',
  },
  {
    id: 'LEAD-02',
    name: 'Leads Inbox',
    path: '/leads/inbox',
    moduleId: 'leads',
    permission: 'leads.view',
    navGroup: 'operating',
    hasNavEntry: false,
    status: 'ready',
    purpose: 'Same lead data as LEAD-01, presented chronologically.',
  },
  {
    id: 'LEAD-03',
    name: 'Lead Detail',
    path: '/leads/:leadId',
    moduleId: 'leads',
    permission: 'leads.view',
    navGroup: 'operating',
    hasNavEntry: false,
    status: 'ready',
    purpose: 'Unified detail for one lead — buyer-inbound or owner-originated.',
  },
  {
    id: 'CUST-01',
    name: 'Customers List',
    path: '/customers',
    moduleId: 'customers',
    permission: 'customers.view',
    navGroup: 'operating',
    hasNavEntry: true,
    status: 'ready',
    purpose: 'Persistent relationship records, independent of any single listing.',
  },
  {
    id: 'CUST-02',
    name: 'Customer Detail',
    path: '/customers/:customerId',
    moduleId: 'customers',
    permission: 'customers.view',
    navGroup: 'operating',
    hasNavEntry: false,
    status: 'ready',
    purpose: 'Unified relationship view — interaction history, linked leads/deals.',
  },
  {
    id: 'OWN-01',
    name: 'Owners List',
    path: '/owners',
    moduleId: 'owners',
    permission: 'owners.view',
    navGroup: 'operating',
    hasNavEntry: true,
    status: 'ready',
    purpose: 'Supply-side counterpart to Customers — property owners.',
  },
  {
    id: 'OWN-02',
    name: 'Owner Detail',
    path: '/owners/:ownerId',
    moduleId: 'owners',
    permission: 'owners.view',
    navGroup: 'operating',
    hasNavEntry: false,
    status: 'ready',
    purpose: 'Single canonical record per owner interaction.',
  },
  {
    id: 'OWN-03',
    name: 'Marketing Requests Queue',
    path: '/owners/marketing-requests',
    moduleId: 'owners',
    permission: 'marketing_requests.view',
    navGroup: 'operating',
    hasNavEntry: false,
    status: 'ready',
    purpose: 'Owner-originated requests for marketing/sale assistance — embedded in Owners, derived onto Today.',
  },
  {
    id: 'CONT-01',
    name: 'Contracts List',
    path: '/contracts',
    moduleId: 'contracts',
    permission: 'contracts.view',
    navGroup: 'operating',
    hasNavEntry: true,
    status: 'ready',
    purpose: 'Every deal as a documented, auditable transaction record.',
  },
  {
    id: 'CONT-02',
    name: 'Contract Detail',
    path: '/contracts/:contractId',
    moduleId: 'contracts',
    permission: 'contracts.view',
    navGroup: 'operating',
    hasNavEntry: false,
    status: 'ready',
    purpose: 'Full lifecycle of one contract — negotiation terms, compliance checklist, documents.',
  },
  {
    id: 'MKT-01',
    name: 'Campaigns List',
    path: '/marketing',
    moduleId: 'marketing',
    permission: 'marketing.view',
    navGroup: 'operating',
    hasNavEntry: true,
    status: 'ready',
    purpose: 'Outbound campaign/promotion management.',
  },
  {
    id: 'MKT-02',
    name: 'Campaign Create/Detail',
    path: '/marketing/new',
    moduleId: 'marketing',
    permission: 'marketing.manage',
    navGroup: 'operating',
    hasNavEntry: false,
    status: 'ready',
    purpose: 'Single flow for creating and later managing a campaign.',
  },
  {
    id: 'MKT-03',
    name: 'Content Quality Queue',
    path: '/marketing/content-quality',
    moduleId: 'marketing',
    permission: 'marketing.manage',
    navGroup: 'operating',
    hasNavEntry: false,
    status: 'ready',
    purpose: 'AI-assisted review queue keeping live inventory content-complete.',
  },

  // ---- Intelligence & Control layer ----
  {
    id: 'FIN-01',
    name: 'Finance Overview',
    path: '/finance',
    moduleId: 'finance',
    permission: 'finance.view',
    navGroup: 'intelligence',
    hasNavEntry: true,
    status: 'placeholder',
    purpose: 'Revenue/commission reporting derived from closed Contracts.',
  },
  {
    id: 'WAL-01',
    name: 'Wallet Overview',
    path: '/wallet',
    moduleId: 'wallet',
    permission: 'wallet.view',
    navGroup: 'intelligence',
    hasNavEntry: true,
    status: 'placeholder',
    purpose: 'Spendable-balance layer — package/quota entitlements, credit balance.',
  },
  {
    id: 'WAL-02',
    name: 'Package/Subscription Detail & Upgrade',
    path: '/wallet/plan',
    moduleId: 'wallet',
    permission: 'wallet.manage',
    navGroup: 'intelligence',
    hasNavEntry: false,
    status: 'placeholder',
    purpose: 'Change tier, view entitlement detail, complete payment.',
  },
  {
    id: 'ANL-01',
    name: 'Analytics Explorer',
    path: '/analytics',
    moduleId: 'analytics',
    permission: 'analytics.view',
    navGroup: 'intelligence',
    hasNavEntry: true,
    status: 'placeholder',
    purpose: 'Exploratory, real-time “how am I doing” layer with Explainability-backed metrics.',
  },
  {
    id: 'RPT-01',
    name: 'Reports List',
    path: '/reports',
    moduleId: 'reports',
    permission: 'reports.view',
    navGroup: 'intelligence',
    hasNavEntry: true,
    status: 'placeholder',
    purpose: 'Generated, exportable, shareable documents.',
  },
  {
    id: 'RPT-02',
    name: 'Report Detail/Builder',
    path: '/reports/new',
    moduleId: 'reports',
    permission: 'reports.view',
    navGroup: 'intelligence',
    hasNavEntry: false,
    status: 'placeholder',
    purpose: 'View a generated report, or compose a custom one.',
  },
  {
    id: 'AUTO-01',
    name: 'Automation Rules List',
    path: '/automation',
    moduleId: 'automation',
    permission: 'automation.view',
    navGroup: 'intelligence',
    hasNavEntry: true,
    status: 'placeholder',
    purpose: 'Visible, editable configuration surface for routing/reminders/follow-ups.',
  },
  {
    id: 'AUTO-02',
    name: 'Automation Rule Editor',
    path: '/automation/new',
    moduleId: 'automation',
    permission: 'automation.manage',
    navGroup: 'intelligence',
    hasNavEntry: false,
    status: 'placeholder',
    purpose: 'Configure a single rule’s trigger/condition/action/threshold.',
  },
  {
    id: 'AICP-01',
    name: 'AI Copilot Conversation',
    path: '/ai-copilot',
    moduleId: 'ai_copilot',
    permission: 'ai_copilot.view',
    featureFlag: 'tbos.ai.copilot',
    navGroup: 'intelligence',
    hasNavEntry: true,
    status: 'placeholder',
    purpose: 'Thin, dedicated surface for open-ended requests.',
  },
  {
    id: 'AICP-02',
    name: 'AI Action Audit Log',
    path: '/ai-copilot/audit-log',
    moduleId: 'ai_copilot',
    permission: 'ai_audit.view',
    featureFlag: 'tbos.ai.copilot',
    navGroup: 'intelligence',
    hasNavEntry: false,
    status: 'placeholder',
    purpose: 'Reviewable record of every AI action taken on the broker’s behalf.',
  },
  {
    id: 'NOTIF-01',
    name: 'Notification Center',
    path: '/notifications',
    moduleId: 'notifications',
    permission: 'notifications.view',
    navGroup: 'intelligence',
    hasNavEntry: true,
    status: 'ready',
    purpose: 'Timeline of every notification the broker has received in-app.',
  },
  {
    id: 'NOTIF-02',
    name: 'Notification Preferences',
    path: '/notifications/preferences',
    moduleId: 'notifications',
    permission: 'notifications.view',
    navGroup: 'intelligence',
    hasNavEntry: false,
    status: 'placeholder',
    purpose: 'Per-type channel opt-in/out, never all-or-nothing.',
  },
  {
    id: 'KB-01',
    name: 'Knowledge Home/Search',
    path: '/knowledge',
    moduleId: 'knowledge',
    permission: 'knowledge.view',
    navGroup: 'intelligence',
    hasNavEntry: true,
    status: 'placeholder',
    purpose: 'Compliance guidance, platform help, explanatory content.',
  },
  {
    id: 'KB-02',
    name: 'Knowledge Article Detail',
    path: '/knowledge/:articleId',
    moduleId: 'knowledge',
    permission: 'knowledge.view',
    navGroup: 'intelligence',
    hasNavEntry: false,
    status: 'placeholder',
    purpose: 'Single article/explanation, deep-linked from Explainability “why” answers.',
  },
  {
    id: 'SET-01',
    name: 'Account & Profile',
    path: '/settings/profile',
    moduleId: 'settings',
    permission: 'settings.profile.edit',
    navGroup: 'intelligence',
    hasNavEntry: true,
    status: 'placeholder',
    purpose: 'Personal account settings.',
  },
  {
    id: 'SET-02',
    name: 'Team & Roles',
    path: '/settings/roles',
    moduleId: 'settings',
    permission: 'settings.roles.manage',
    navGroup: 'intelligence',
    hasNavEntry: false,
    status: 'placeholder',
    purpose: 'The real RBAC surface — role creation, scoped permission assignment.',
  },
  {
    id: 'SET-03',
    name: 'Integrations',
    path: '/settings/integrations',
    moduleId: 'settings',
    permission: 'settings.integrations.manage',
    navGroup: 'intelligence',
    hasNavEntry: false,
    status: 'placeholder',
    purpose: 'Manage third-party/government integration credentials and connections.',
  },
  {
    id: 'SET-04',
    name: 'Compliance Documents',
    path: '/settings/compliance',
    moduleId: 'settings',
    permission: 'settings.compliance.view',
    navGroup: 'intelligence',
    hasNavEntry: false,
    status: 'placeholder',
    purpose: 'Nafath/FAL/REGA credentials and documents.',
  },

  // ---- Cross-cutting overlays ----
  {
    id: 'GS-01',
    name: 'Global Search Results',
    path: '/search',
    moduleId: 'home',
    permission: null,
    navGroup: 'cross-cutting',
    hasNavEntry: false,
    status: 'placeholder',
    purpose: 'Primary navigation method for any list beyond a handful of items.',
  },
  {
    id: 'QA-01',
    name: 'Quick Actions panel',
    path: '',
    moduleId: 'home',
    permission: null,
    navGroup: 'cross-cutting',
    hasNavEntry: false,
    overlayOnly: true,
    status: 'ready',
    purpose: '2-tap capture of the top-4 JTBD-ranked actions.',
  },
  {
    id: 'CMD-01',
    name: 'Command Palette',
    path: '',
    moduleId: 'home',
    permission: null,
    navGroup: 'cross-cutting',
    hasNavEntry: false,
    overlayOnly: true,
    status: 'ready',
    purpose: 'Keyboard-power-user superset of Global Search.',
  },
  {
    id: 'ONB-01',
    name: 'Guided Onboarding',
    path: '/onboarding',
    moduleId: 'home',
    permission: null,
    navGroup: 'cross-cutting',
    hasNavEntry: false,
    status: 'placeholder',
    purpose: 'Replaces a blank dashboard for a new account with a guided first-use path.',
  },

  // ---- Platform Console (ADM only, architecturally separate) ----
  {
    id: 'PC-01',
    name: 'Content & User Review',
    path: '/console/moderation',
    moduleId: 'platform_console',
    permission: 'platform_console.access',
    navGroup: 'platform-console',
    hasNavEntry: true,
    status: 'placeholder',
    purpose: 'Review flagged listings/users.',
  },
  {
    id: 'PC-02',
    name: 'Reference Data',
    path: '/console/reference-data',
    moduleId: 'platform_console',
    permission: 'platform_console.access',
    navGroup: 'platform-console',
    hasNavEntry: true,
    status: 'placeholder',
    purpose: 'Maintain reference data (cities, categories, property types, districts).',
  },
  {
    id: 'PC-03',
    name: 'Platform Compliance Oversight',
    path: '/console/compliance',
    moduleId: 'platform_console',
    permission: 'platform_console.access',
    navGroup: 'platform-console',
    hasNavEntry: true,
    status: 'placeholder',
    purpose: 'Platform-wide compliance oversight.',
  },
  {
    id: 'PC-04',
    name: 'Escalations',
    path: '/console/support',
    moduleId: 'platform_console',
    permission: 'platform_console.access',
    navGroup: 'platform-console',
    hasNavEntry: true,
    status: 'placeholder',
    purpose: 'Escalated support/compliance issue handling.',
  },
  {
    id: 'PC-05',
    name: 'Platform Configuration',
    path: '/console/configuration',
    moduleId: 'platform_console',
    permission: 'platform_console.access',
    navGroup: 'platform-console',
    hasNavEntry: true,
    status: 'placeholder',
    purpose: 'Platform-level configuration.',
  },
];

export const SCREEN_MAP: Record<string, ScreenDefinition> = Object.fromEntries(SCREEN_REGISTRY.map((s) => [s.id, s]));

export const ROUTABLE_SCREENS = SCREEN_REGISTRY.filter((s) => !s.overlayOnly && s.path);

/**
 * Split by architectural boundary (Constitution Article V) — app/router builds
 * two entirely separate route subtrees from these, never one combined list, so
 * a Platform Console screen can never end up nested under the Broker OS's
 * AppShell (or vice versa) by accident of iteration order.
 */
export const BROKER_ROUTABLE_SCREENS = ROUTABLE_SCREENS.filter((s) => s.navGroup !== 'platform-console');
export const CONSOLE_ROUTABLE_SCREENS = ROUTABLE_SCREENS.filter((s) => s.navGroup === 'platform-console');

/** The single screen a module's rail/tab entry links to — its first `hasNavEntry`
 * screen in registry order (e.g. Properties → PROP-01, not PROP-02/03). */
export function primaryScreenForModule(moduleId: string): ScreenDefinition | undefined {
  return SCREEN_REGISTRY.find((s) => s.moduleId === moduleId && s.hasNavEntry);
}
