/**
 * Traceability registry for the first Vertical Slice (master prompt §63/§41):
 * Today → Leads → Lead Detail → Lead Action → Notification, extended in
 * Phase 6 with the Properties Vertical Slice (Properties List → Property
 * Detail → Compliance/Media/Performance/History → Property Action), and in
 * Phase 7 with the Relationship Vertical Slice (Customers List → Customer
 * Detail ↔ Owners List → Owner Detail ↔ Marketing Requests), in Phase 8 with
 * the Contracts + Compliance Vertical Slice, and in Phase 9 with the
 * Marketing + Campaign Intelligence Vertical Slice (Campaigns List →
 * Campaign Create/Detail → eligibility gate ↔ Content Quality Queue). For
 * each screen: screenId (cross-checked against registry/screens/
 * screenRegistry.ts), route, purpose, components consumed, permissions
 * enforced, states implemented, data source, mock data origin, tests, and
 * the exact blueprint document the screen traces back to. See
 * TBOS_UI_VERTICAL_SLICE_REPORT.md, TBOS_PROPERTIES_VERTICAL_SLICE_REPORT.md,
 * TBOS_RELATIONSHIP_VERTICAL_SLICE_REPORT.md,
 * TBOS_CONTRACTS_COMPLIANCE_VERTICAL_SLICE_REPORT.md, and
 * TBOS_MARKETING_VERTICAL_SLICE_REPORT.md for the full narratives.
 */
export interface VerticalSliceScreenRecord {
  screenId: string;
  route: string;
  purpose: string;
  components: string[];
  permissions: string[];
  states: string[];
  dataSource: string;
  mockData: string;
  tests: string[];
  blueprintReference: string;
}

export const VERTICAL_SLICE_REGISTRY: VerticalSliceScreenRecord[] = [
  {
    screenId: 'TODAY-01',
    route: '/today',
    purpose: "The broker's operational command center — ranked recommendations, never a bare KPI dashboard.",
    components: ['RecommendationCard (new)', 'StatusBadge', 'ExplainabilityPopover', 'EmptyState', 'ErrorState', 'Skeleton'],
    permissions: ['today.view (route)', 'today.act (implicit — all Today-viewing roles hold it)'],
    states: ['loading', 'populated', 'empty (positive "caught up")', 'error'],
    dataSource: 'lib/api/endpoints/today.ts → lib/today/useToday.ts (React Query)',
    mockData: 'lib/today/computeRecommendations.ts, computed from mocks/api/db.ts leads + tasks (no fabricated content — every entry traces to a real Lead/Task record)',
    tests: ['src/tests/verticalSlice.test.tsx — TODAY-01 describe block (2 tests)'],
    blueprintReference: 'tbos-blueprint/04_SCREEN_INVENTORY.md TODAY-01; tbos-blueprint/07_DECISION_SUPPORT_SYSTEM.md "the rule"',
  },
  {
    screenId: 'LEAD-01',
    route: '/leads',
    purpose: 'The Unified Lead Pipeline — kanban-style stage view of every lead, buyer-inbound and owner-originated, in one system.',
    components: ['KanbanBoard', 'KanbanCard', 'EntityAvatar', 'SlaTimer (new)', 'Badge', 'FilterBar'],
    permissions: ['leads.view (route + record-list scoping)', 'leads.view.team (agency/team-wide visibility)', 'leads.respond (stage-move gate)'],
    states: ['loading', 'populated', 'empty', 'filtered/no-results', 'error'],
    dataSource: 'lib/api/endpoints/leads.ts → lib/leads/useLeads.ts + lib/leads/useLeadMutations.ts (React Query)',
    mockData: 'mocks/data/seed.ts LEADS, scoped by mocks/api/db.ts leadsForUser() (own vs. team/agency per role)',
    tests: ['src/tests/verticalSlice.test.tsx — LEAD-01 describe block (2 tests: PC scoping, SM team visibility)'],
    blueprintReference: 'tbos-blueprint/04_SCREEN_INVENTORY.md LEAD-01; tbos-blueprint/06_STATE_ARCHITECTURE.md Lead pipeline stages',
  },
  {
    screenId: 'LEAD-02',
    route: '/leads/inbox',
    purpose: 'Same lead data as LEAD-01, presented chronologically — a view toggle, not a separate destination.',
    components: ['DataTable', 'LeadStageBadge', 'SlaTimer (new)', 'Badge', 'BulkActionBar', 'Dropdown', 'PermissionGate'],
    permissions: ['leads.view (route + scoping, same query as LEAD-01)', 'leads.assign (bulk-reassign gate)'],
    states: ['loading', 'populated', 'empty', 'error'],
    dataSource: 'lib/leads/useLeads.ts (identical query key/cache entry as LEAD-01)',
    mockData: 'Same as LEAD-01 — one query, two presentations',
    tests: ['Covered indirectly — same useLeads() hook exercised by LEAD-01 tests; DataTable itself covered by src/tests/patterns.test.tsx'],
    blueprintReference: 'tbos-blueprint/04_SCREEN_INVENTORY.md LEAD-02',
  },
  {
    screenId: 'LEAD-03',
    route: '/leads/:leadId',
    purpose: 'Unified detail for one lead — identity, context, timeline, status, actions, permissions, next step.',
    components: [
      'EntityDetailHeader',
      'LeadStageBadge',
      'MetricWithExplanation',
      'ExplainabilityPopover',
      'ActivityTimeline',
      'Dropdown',
      'Drawer',
      'Field',
      'Select',
      'Textarea',
      'Input',
      'PermissionGate',
      'Tooltip',
      'NoPermissionState',
    ],
    permissions: [
      'leads.view (route)',
      'record-level scope check in-screen: assignee OR leads.view.team (TBOS_UI_INTEGRATION_AUDIT.md §1.J)',
      'leads.respond (respond/change-stage/note/follow-up/mark-lost/reopen gate)',
      'leads.assign (reassign gate)',
    ],
    states: ['loading', 'populated (open)', 'populated (lost, with reason)', 'populated (won)', 'restricted (record-level)', 'error', 'not_found'],
    dataSource: 'lib/api/endpoints/leads.ts → lib/leads/useLead.ts (React Query + mutations)',
    mockData: 'mocks/data/seed.ts LEADS + LEAD_ACTIVITIES, mutated via mocks/api/db.ts (changeStage/reassign/markLost/reopen/addNote/logOutsideResponse/scheduleFollowUp)',
    tests: ['src/tests/verticalSlice.test.tsx — LEAD-03 describe block (4 tests: record-scope denial, stage change, mark-lost-with-reason, disabled-reassign)'],
    blueprintReference: 'tbos-blueprint/04_SCREEN_INVENTORY.md LEAD-03',
  },
  {
    screenId: 'LEAD Actions',
    route: '(panel/drawer on LEAD-01 and LEAD-03 — no dedicated route; no LEAD-04 ID exists in the blueprint)',
    purpose: 'Respond, change stage, reassign, convert to Contract, mark Lost (required reason), log outside response, add note, schedule follow-up.',
    components: ['Dropdown (stage/reassign)', 'Drawer (note/follow-up/log-response/mark-lost)', 'Select (lost reason)', 'ConfirmationDialog pattern superseded by Drawer for Mark Lost — see report'],
    permissions: ['leads.respond', 'leads.assign'],
    states: ['idle', 'open (drawer/dropdown)', 'submitting', 'confirmed'],
    dataSource: 'lib/leads/useLead.ts mutations',
    mockData: 'mocks/api/db.ts mutation helpers, each appending a LeadActivity entry',
    tests: ['src/tests/verticalSlice.test.tsx (stage change, mark lost)'],
    blueprintReference: 'tbos-blueprint/04_SCREEN_INVENTORY.md LEAD-03 Primary/Secondary actions',
  },
  {
    screenId: 'NOTIF-01',
    route: '/notifications',
    purpose: 'Timeline of every notification the broker has received in-app — deep-links to source, never a dead end.',
    components: ['NotificationItem (unchanged from TopBar dropdown)', 'EmptyState', 'ErrorState', 'Skeleton'],
    permissions: ['notifications.view (route)'],
    states: ['loading', 'unread present', 'all read', 'empty (positive)', 'filtered (unread-only)', 'error'],
    dataSource: 'lib/notifications/useNotifications.ts (pre-existing, reused unchanged)',
    mockData: 'mocks/data/seed.ts NOTIFICATIONS, extended with optional sourceRecordId for lead-specific deep-linking',
    tests: ['src/tests/verticalSlice.test.tsx — NOTIF-01 describe block (1 test: deep-link navigation)'],
    blueprintReference: 'tbos-blueprint/04_SCREEN_INVENTORY.md NOTIF-01; tbos-blueprint/09_NOTIFICATION_BLUEPRINT.md',
  },
  {
    screenId: 'PROP-01',
    route: '/properties',
    purpose: "The agency's property inventory — search-first, filterable list; scoped by role, never just a static table of listings.",
    components: ['PageHeader', 'FilterBar', 'DataTable', 'PropertyStatusBadge', 'EntityAvatar', 'BulkActionBar', 'PermissionGate', 'ConfirmationDialog', 'EmptyState (brand pattern)', 'ErrorState', 'Skeleton'],
    permissions: ['properties.view (route + record-list scoping via scopeFor())', 'properties.delete (bulk-archive gate)'],
    states: ['loading', 'populated', 'empty (brand-pattern illustration)', 'filtered/no-results', 'error'],
    dataSource: 'lib/api/endpoints/properties.ts → lib/properties/useProperties.ts (React Query, typed <TData, ApiError> from the start)',
    mockData: 'mocks/data/seed.ts PROPERTIES, scoped by mocks/api/db.ts propertiesForUser() (own vs. agency-wide per role, via scopeFor())',
    tests: ['src/tests/properties.test.tsx — PROP-01 describe block (2 tests: PC own-scope + no-results, AO agency-wide visibility)'],
    blueprintReference: 'tbos-definition/07_INFORMATION_ARCHITECTURE.md Properties module; tbos-blueprint/04_SCREEN_INVENTORY.md PROP-01',
  },
  {
    screenId: 'PROP-02',
    route: '/properties/:propertyId',
    purpose: 'Unified detail for one property — inventory, compliance, media, performance, lifecycle, and activity in one record, with state-dependent actions.',
    components: [
      'EntityDetailHeader',
      'PropertyStatusBadge',
      'Tabs (Overview/Media/Compliance/Performance/History — tabs per tbos-definition IA, not sub-routes)',
      'Alert (lifecycle message)',
      'MetricWithExplanation',
      'Badge',
      'ActivityTimeline',
      'Dropdown',
      'Drawer',
      'Field',
      'Input',
      'PermissionGate',
      'Tooltip',
      'ConfirmationDialog',
      'NoPermissionState',
    ],
    permissions: [
      'properties.view (route)',
      'record-level scope check in-screen: brokerId === current user OR agency-wide properties.view (mirrors LEAD-03 pattern)',
      'properties.edit (change price)',
      'properties.compliance.edit (verify/resolve compliance requirement — held by Operations Manager even without properties.edit)',
      'properties.delete (reassign + archive gate)',
    ],
    states: [
      'loading',
      'populated (draft/pending_compliance/active/expiring/expired/rejected/sold_rented/archived)',
      'compliance-blocked (explicit missing/pending/expired requirement, never a bare badge)',
      'restricted (record-level)',
      'error',
      'not_found',
    ],
    dataSource: 'lib/api/endpoints/properties.ts → lib/properties/useProperty.ts (React Query + mutations)',
    mockData: 'mocks/data/seed.ts PROPERTIES + PROPERTY_COMPLIANCE + PROPERTY_MEDIA + PROPERTY_ACTIVITIES, mutated via mocks/api/db.ts (changePrice/publish/archive/markSoldRented/renewCompliance/resubmit/reassign/resolveComplianceRequirement)',
    tests: ['src/tests/properties.test.tsx — PROP-02 describe block (5 tests: record-scope denial, compliance-blocked banner, disabled-reassign, OM compliance resolution, AO archive)'],
    blueprintReference: 'tbos-definition/07_INFORMATION_ARCHITECTURE.md "Property Detail (tabs, not sub-pages)"; tbos-blueprint/04_SCREEN_INVENTORY.md PROP-02',
  },
  {
    screenId: 'CUST-01',
    route: '/customers',
    purpose: 'Persistent relationship records, independent of any single listing — search-first list scoped by role.',
    components: ['PageHeader', 'FilterBar', 'DataTable', 'EntityAvatar (kind="person")', 'Badge', 'Select', 'EmptyState', 'ErrorState', 'Skeleton'],
    permissions: ['customers.view (route + record-list scoping via scopeFor(), derived transitively through the viewer’s Leads — Customer has no stored assigneeId)'],
    states: ['loading', 'populated', 'empty', 'filtered/no-results', 'error'],
    dataSource: 'lib/api/endpoints/customers.ts → lib/customers/useCustomers.ts (React Query, typed <TData, ApiError> from the start)',
    mockData: 'mocks/data/seed.ts CUSTOMERS, scoped by mocks/api/db.ts customersForUser() (own vs. agency-wide per role); leadCount/lastActivityAt computed fresh from Lead.customerId and CustomerActivity, never stored',
    tests: ['src/tests/relationships.test.tsx — CUST-01 describe block (3 tests: PC own-scope via linked leads, AO agency-wide visibility, SM route-level denial)'],
    blueprintReference: 'tbos-definition/16_MODULE_SPECIFICATIONS.md Customers; tbos-blueprint/04_SCREEN_INVENTORY.md CUST-01',
  },
  {
    screenId: 'CUST-02',
    route: '/customers/:customerId',
    purpose: 'Unified relationship view — interaction history, linked leads/deals, one inline chronological timeline (no tabs, unlike PROP-02/OWN-02).',
    components: ['EntityDetailHeader (title as ReactNode)', 'Badge', 'EntityCard (linked-lead relationships)', 'ActivityTimeline', 'Drawer', 'Field', 'Textarea', 'PermissionGate', 'EmptyState', 'NoPermissionState', 'ErrorState', 'Skeleton'],
    permissions: [
      'customers.view (route)',
      'record-level scope check in-screen: any linked Lead assigned to the viewer OR agency-wide customers.view (mirrors LEAD-03/PROP-02 pattern)',
      'customers.edit (log-interaction gate)',
    ],
    states: ['loading', 'populated (with/without linked leads)', 'restricted (record-level)', 'error', 'not_found'],
    dataSource: 'lib/api/endpoints/customers.ts → lib/customers/useCustomer.ts (React Query + logInteraction mutation)',
    mockData: 'mocks/data/seed.ts CUSTOMERS + CUSTOMER_ACTIVITIES, mutated via mocks/api/db.ts logCustomerInteraction(); linked Leads read live via leadsForCustomer() (Lead.customerId, the authoritative FK)',
    tests: ['src/tests/relationships.test.tsx — CUST-02 describe block (3 tests: record-scope denial, click-through to canonical Lead Detail, log-interaction end-to-end)'],
    blueprintReference: 'tbos-blueprint/04_SCREEN_INVENTORY.md CUST-02; tbos-blueprint/02_NAVIGATION_BLUEPRINT.md "Inline timeline, not a panel"',
  },
  {
    screenId: 'OWN-01',
    route: '/owners',
    purpose: 'Supply-side counterpart to Customers — property owners and their relationship to the agency.',
    components: ['PageHeader', 'FilterBar', 'DataTable', 'EntityAvatar (kind="person")', 'Badge', 'Checkbox', 'EmptyState', 'ErrorState', 'Skeleton'],
    permissions: ['owners.view (route + record-list scoping via scopeFor(), derived transitively through the viewer’s Properties — Owner has no stored brokerId)'],
    states: ['loading', 'populated', 'empty', 'filtered (open-requests-only)', 'error'],
    dataSource: 'lib/api/endpoints/owners.ts → lib/owners/useOwners.ts (React Query, typed <TData, ApiError> from the start)',
    mockData: 'mocks/data/seed.ts OWNERS, scoped by mocks/api/db.ts ownersForUser() (own vs. agency-wide per role); propertyCount/openMarketingRequestCount computed fresh from Property.ownerId and MarketingRequest.status, never stored',
    tests: ['src/tests/relationships.test.tsx — OWN-01 describe block (1 test: cross-agency exclusion)'],
    blueprintReference: 'tbos-definition/16_MODULE_SPECIFICATIONS.md Owners; tbos-blueprint/04_SCREEN_INVENTORY.md OWN-01',
  },
  {
    screenId: 'OWN-02',
    route: '/owners/:ownerId',
    purpose: 'Single canonical record per owner interaction — linked properties, Marketing Requests, and activity, with state-dependent actions.',
    components: [
      'EntityDetailHeader',
      'EntityCard (linked-property relationships)',
      'PropertyStatusBadge',
      'Tabs (Overview/Marketing Requests/Activity — tab pattern per tbos-blueprint "same as PROP-02"; OWN-03 content embedded here as a tab, never a separate route)',
      'Badge',
      'ActivityTimeline',
      'Drawer',
      'Field',
      'Select',
      'PermissionGate',
      'EmptyState',
      'NoPermissionState',
      'ErrorState',
      'Skeleton',
    ],
    permissions: [
      'owners.view (route)',
      'record-level scope check in-screen: any linked Property brokered by the viewer OR agency-wide owners.view (mirrors LEAD-03/PROP-02/CUST-02 pattern)',
      'marketing_requests.respond (respond/mark-won/mark-lost gate)',
    ],
    states: ['loading', 'populated (with/without linked properties)', 'populated (with/without marketing requests)', 'restricted (record-level)', 'error', 'not_found'],
    dataSource: 'lib/api/endpoints/owners.ts → lib/owners/useOwner.ts (React Query + respondToRequest/markRequestWon/markRequestLost mutations, also lib/api/endpoints/marketingRequests.ts)',
    mockData: 'mocks/data/seed.ts OWNERS + OWNER_ACTIVITIES + MARKETING_REQUESTS, mutated via mocks/api/db.ts (respondToMarketingRequest/markMarketingRequestWon/markMarketingRequestLost); linked Properties read live via propertiesForOwner() (Property.ownerId, the authoritative FK — the exact drift this phase found and fixed, see TBOS_RELATIONSHIP_UX_AUDIT.md P1-3)',
    tests: ['src/tests/relationships.test.tsx — OWN-02 describe block (3 tests: record-scope denial, P1-3 FK-derived property regression, Marketing Request Open→In Progress state transition)'],
    blueprintReference: 'tbos-blueprint/04_SCREEN_INVENTORY.md OWN-02; tbos-blueprint/06_STATE_ARCHITECTURE.md "Marketing Request states"',
  },
  {
    screenId: 'OWN-03',
    route: '/owners/marketing-requests',
    purpose: 'Agency-wide Marketing Requests queue — the same MarketingRequest records OWN-02’s tab shows scoped to one owner, never a second data source (LEAD-01/LEAD-02’s "same query, two presentations" precedent).',
    components: ['PageHeader', 'DataTable', 'Badge', 'EmptyState', 'ErrorState', 'Skeleton'],
    permissions: ['marketing_requests.view (route + scoping: MM/AO agency-wide, PC/SB matched-only, via marketingRequestsForUser())'],
    states: ['loading', 'populated', 'empty', 'error'],
    dataSource: 'lib/api/endpoints/marketingRequests.ts → lib/owners/useMarketingRequestsQueue.ts (React Query)',
    mockData: 'Same MARKETING_REQUESTS records as OWN-02’s tab — no duplicate data source',
    tests: ['Covered indirectly — same marketingRequestsForUser()/respond mutation exercised by OWN-02 tests; row click resolves to the same canonical OWN-02 screen (no per-entry-point duplicate implementation)'],
    blueprintReference: 'tbos-blueprint/04_SCREEN_INVENTORY.md OWN-03; tbos-blueprint/02_NAVIGATION_BLUEPRINT.md "the one deliberate cross-surface exception — reached via Owners or Today, never a rail item of its own"',
  },
  {
    screenId: 'CONT-01',
    route: '/contracts',
    purpose: 'Every deal as a documented, auditable transaction record — search-first list scoped by role, covering all 6 canonical lifecycle stages.',
    components: ['PageHeader', 'FilterBar', 'DataTable', 'EntityAvatar (kind="record")', 'ContractStatusBadge (new)', 'EmptyState', 'ErrorState', 'Skeleton'],
    permissions: ['contracts.view (route + record-list scoping via scopeFor(), derived transitively through the linked Lead’s assigneeId — Contract has no stored assignee)'],
    states: ['loading', 'populated', 'empty', 'filtered (by stage)/no-results', 'error'],
    dataSource: 'lib/api/endpoints/contracts.ts → lib/contracts/useContracts.ts (React Query, typed <TData, ApiError> from the start)',
    mockData: 'mocks/data/seed.ts CONTRACTS, scoped by mocks/api/db.ts contractsForUser() (own vs. agency-wide per role, via the linked Lead’s assigneeId)',
    tests: ['src/tests/contracts.test.tsx — CONT-01 describe block (3 tests: PC own-scope via linked leads, AO agency-wide visibility incl. cross-agency exclusion, route-level denial)'],
    blueprintReference: 'tbos-definition/07_INFORMATION_ARCHITECTURE.md Contracts module; tbos-blueprint/06_STATE_ARCHITECTURE.md Contract lifecycle (Draft/Pending Compliance/Active/Renewal Due/Closed/Cancelled)',
  },
  {
    screenId: 'CONT-02',
    route: '/contracts/:contractId',
    purpose: 'A contract operating system, not CRUD — compliance blockers, next actions, and Contract↔Lead/Customer/Owner/Property relationships in one record, single page (no tabs, confirmed absent from the CONT-02 component-mapping table, unlike PROP-02/OWN-02).',
    components: [
      'EntityDetailHeader (title as clickable customer link)',
      'ContractStatusBadge (new)',
      'Alert (lifecycle message)',
      'MetricWithExplanation',
      'ComplianceChecklist (extended: optional per-item action slot)',
      'ComplianceDocument',
      'ActivityTimeline',
      'Drawer',
      'Field',
      'Textarea',
      'PermissionGate',
      'Tooltip',
      'NoPermissionState',
    ],
    permissions: [
      'contracts.view (route)',
      'record-level scope check in-screen: linked Lead’s assigneeId === viewer OR agency-wide contracts.view, ANDed with contract.agencyId === viewer.agencyId (P0 fix — see below)',
      'contracts.approve (activate/renew/decline-renewal/cancel gate — OM/AO only)',
    ],
    states: [
      'loading',
      'populated (draft/pending_compliance/active/renewal_due/closed/cancelled)',
      'compliance-blocked (explicit mismatch/incomplete requirement with reason, never a bare disabled button)',
      'restricted (record-level)',
      'error',
      'not_found',
    ],
    dataSource: 'lib/api/endpoints/contracts.ts → lib/contracts/useContract.ts (React Query + mutations)',
    mockData: 'mocks/data/seed.ts CONTRACTS + CONTRACT_COMPLIANCE + CONTRACT_DOCUMENTS + CONTRACT_ACTIVITIES, mutated via mocks/api/db.ts (startComplianceChecklist/resolveContractComplianceItem/activateContract/renewContract/declineContractRenewal/cancelContract); linked-property compliance checked live via linkedPropertyComplianceVerified() (computed, never stored — Phase 7 P1-3 anti-drift precedent)',
    tests: [
      'src/tests/contracts.test.tsx — CONT-02 describe block (5 tests: teammate-lead denial, cross-agency denial (P0 regression), compliance-blocked banner with mismatch detail, OM activation happy path, disabled-explained Activate for non-approver, reasoned cancellation)',
      'src/tests/contracts.test.tsx — Cross-entity navigation + Today integration describe blocks (3 tests)',
    ],
    blueprintReference: 'tbos-blueprint/04_SCREEN_INVENTORY.md CONT-02; tbos-blueprint/01_EXPERIENCE_ARCHITECTURE.md WF-CONTRACT-NEW',
  },
  {
    screenId: 'MKT-01',
    route: '/marketing',
    purpose: 'Outbound campaign/promotion management — distinct from inbound Marketing Requests (OWN-03), never the same data source.',
    components: ['PageHeader', 'FilterBar', 'DataTable', 'EntityAvatar (kind="record")', 'Badge', 'EmptyState (brand pattern)', 'ErrorState', 'Skeleton'],
    permissions: ['marketing.view (route + record-list scoping via scopeFor() — own for SB, agency-wide for AO/MM)'],
    states: ['loading', 'populated', 'empty (brand-pattern illustration)', 'filtered (by status)/no-results', 'error'],
    dataSource: 'lib/api/endpoints/marketing.ts → lib/marketing/useCampaigns.ts (React Query)',
    mockData: 'mocks/data/seed.ts CAMPAIGNS, scoped by mocks/api/db.ts campaignsForUser() (own vs. agency-wide per role)',
    tests: ['src/tests/marketing.test.tsx — MKT-01 describe block (2 tests: AO agency-wide visibility incl. cross-agency exclusion, route-level denial)'],
    blueprintReference: 'tbos-definition/16_MODULE_SPECIFICATIONS.md Marketing; tbos-blueprint/04_SCREEN_INVENTORY.md MKT-01',
  },
  {
    screenId: 'MKT-02',
    route: '/marketing/new',
    purpose: 'Single flow for creating and later managing a campaign — eligibility checked before inventory-selection UI even renders (TBOS_MARKETING_UX_AUDIT.md\'s resolution: an optional ?campaignId= query param distinguishes create from manage on the one registered route).',
    components: [
      'EntityDetailHeader',
      'Badge',
      'Alert (lifecycle message)',
      'MetricWithExplanation',
      'QuotaBalanceMeter (first real consumer — registry-accuracy fix)',
      'AISuggestion + AIActionBar (first real consumer)',
      'Checkbox',
      'ConfirmationDialog',
      'EmptyState (zero-eligible, brand pattern)',
      'ActivityTimeline',
      'PermissionGate',
      'Tooltip',
      'NoPermissionState',
    ],
    permissions: [
      'marketing.view (route)',
      'record-level scope check in-screen: campaign.agencyId === viewer.agencyId, ANDed with own-scope createdByUserId check (P0 pattern applied proactively from day one)',
      'marketing.manage (create/select-inventory/launch/pause/end gate)',
    ],
    states: [
      'loading',
      'create (no campaignId)',
      'populated (draft/running/paused/ended)',
      'zero-eligible-inventory (never even renders the checkbox list, per spec)',
      'launch-blocked (no-inventory-selected/no-longer-eligible/insufficient-balance, each with a specific reason)',
      'restricted (record-level)',
      'error',
      'not_found',
    ],
    dataSource: 'lib/api/endpoints/marketing.ts → lib/marketing/useCampaign.ts (React Query + create/selectInventory/launch/pause/end mutations)',
    mockData:
      'mocks/data/seed.ts CAMPAIGNS + CAMPAIGN_ACTIVITIES, mutated via mocks/api/db.ts (createCampaign/selectCampaignInventory/launchCampaign/pauseCampaign/endCampaign); eligible inventory computed live via eligiblePropertiesForUser() (active/expiring Properties, never a stored snapshot)',
    tests: [
      'src/tests/marketing.test.tsx — MKT-02 describe block (6 tests: cross-agency denial (P0), create flow, zero-eligible block, disabled-explained Launch with no selection, full launch happy path with quota consumption, resume-paused re-validating eligibility)',
    ],
    blueprintReference: 'tbos-definition/09_WORKFLOW_ARCHITECTURE.md Marketing Campaign workflow; tbos-blueprint/04_SCREEN_INVENTORY.md MKT-02',
  },
  {
    screenId: 'MKT-03',
    route: '/marketing/content-quality',
    purpose: 'AI-assisted review queue keeping live inventory content-complete — a transparent completeness checklist (photos/description/price), not a fabricated AI score.',
    components: ['PageHeader', 'Badge', 'AISuggestion + AIActionBar', 'Field', 'Textarea', 'EmptyState (positive tone)', 'ErrorState', 'Skeleton'],
    permissions: ['marketing.manage (route + scoping — same grant as MKT-02\'s manage actions)'],
    states: ['loading', 'populated (worst-first)', 'empty (positive — "all listings meet the quality bar")', 'error'],
    dataSource: 'lib/api/endpoints/marketing.ts → lib/marketing/useContentQualityQueue.ts (React Query + updateDescription mutation)',
    mockData:
      'Computed live via mocks/api/db.ts contentQualityQueueForUser() from real Property + PropertyMedia records (lib/marketing/contentQuality.ts evaluatePropertyContentQuality()) — never a stored score. Property.description (new, optional field) added to support the description-length check.',
    tests: [
      'src/tests/marketing.test.tsx — MKT-03 describe block (3 tests: surfaces a low-quality listing with correct missing-item badges, route-level denial, accept-fix-suggestion re-scores live)',
      'src/tests/marketing.test.tsx — Today integration describe block (2 tests: content_quality signal gated to marketing.manage)',
    ],
    blueprintReference: 'tbos-blueprint/04_SCREEN_INVENTORY.md MKT-03; tbos-blueprint/08_AI_INTERACTION_BLUEPRINT.md Property Quality capability',
  },
];
