import type { ModuleDefinition } from '@/types/modules';

/**
 * Module registry — one entry per IA module in tbos-definition/07_INFORMATION_ARCHITECTURE.md
 * and tbos-blueprint/02_NAVIGATION_BLUEPRINT.md §1's three-group rail. Navigation
 * components read this instead of hardcoding module behavior (master prompt §10).
 */
export const MODULE_REGISTRY: ModuleDefinition[] = [
  {
    id: 'home',
    name: 'Home',
    routePrefix: '/home',
    navGroup: 'orientation',
    icon: 'home',
    visibilityPermission: 'home.view',
    defaultExpandedForRoles: 'all',
    status: 'foundation',
  },
  {
    id: 'today',
    name: 'Today',
    routePrefix: '/today',
    navGroup: 'orientation',
    icon: 'zap',
    visibilityPermission: 'today.view',
    defaultExpandedForRoles: 'all',
    status: 'foundation',
  },
  {
    id: 'tasks',
    name: 'Tasks',
    routePrefix: '/tasks',
    navGroup: 'orientation',
    icon: 'check-square',
    visibilityPermission: 'tasks.view',
    defaultExpandedForRoles: 'all',
    status: 'foundation',
  },

  {
    id: 'properties',
    name: 'Properties',
    routePrefix: '/properties',
    navGroup: 'operating',
    icon: 'building',
    visibilityPermission: 'properties.view',
    defaultExpandedForRoles: 'all',
    status: 'foundation',
  },
  {
    id: 'projects',
    name: 'Projects',
    routePrefix: '/projects',
    navGroup: 'operating',
    icon: 'layers',
    visibilityPermission: 'projects.view',
    defaultExpandedForRoles: 'all',
    status: 'foundation',
  },
  {
    id: 'leads',
    name: 'Leads',
    routePrefix: '/leads',
    navGroup: 'operating',
    icon: 'target',
    visibilityPermission: 'leads.view',
    defaultExpandedForRoles: 'all',
    status: 'foundation',
  },
  {
    id: 'customers',
    name: 'Customers',
    routePrefix: '/customers',
    navGroup: 'operating',
    icon: 'users',
    visibilityPermission: 'customers.view',
    defaultExpandedForRoles: 'all',
    status: 'foundation',
  },
  {
    id: 'owners',
    name: 'Owners',
    routePrefix: '/owners',
    navGroup: 'operating',
    icon: 'user-check',
    visibilityPermission: 'owners.view',
    defaultExpandedForRoles: 'all',
    status: 'foundation',
  },
  {
    id: 'contracts',
    name: 'Contracts',
    routePrefix: '/contracts',
    navGroup: 'operating',
    icon: 'file-text',
    visibilityPermission: 'contracts.view',
    defaultExpandedForRoles: 'all',
    status: 'foundation',
  },
  {
    id: 'marketing',
    name: 'Marketing',
    routePrefix: '/marketing',
    navGroup: 'operating',
    icon: 'megaphone',
    visibilityPermission: 'marketing.view',
    defaultExpandedForRoles: 'all',
    status: 'foundation',
  },

  {
    id: 'finance',
    name: 'Finance',
    routePrefix: '/finance',
    navGroup: 'intelligence',
    icon: 'banknote',
    visibilityPermission: 'finance.view',
    defaultExpandedForRoles: ['AO', 'OM'],
    status: 'foundation',
  },
  {
    id: 'wallet',
    name: 'Wallet',
    routePrefix: '/wallet',
    navGroup: 'intelligence',
    icon: 'wallet',
    visibilityPermission: 'wallet.view',
    defaultExpandedForRoles: ['AO', 'OM'],
    status: 'foundation',
  },
  {
    id: 'analytics',
    name: 'Analytics',
    routePrefix: '/analytics',
    navGroup: 'intelligence',
    icon: 'bar-chart',
    visibilityPermission: 'analytics.view',
    defaultExpandedForRoles: ['AO', 'OM'],
    status: 'foundation',
  },
  {
    id: 'reports',
    name: 'Reports',
    routePrefix: '/reports',
    navGroup: 'intelligence',
    icon: 'clipboard-list',
    visibilityPermission: 'reports.view',
    defaultExpandedForRoles: ['AO', 'OM'],
    status: 'foundation',
  },
  {
    id: 'automation',
    name: 'Automation',
    routePrefix: '/automation',
    navGroup: 'intelligence',
    icon: 'workflow',
    visibilityPermission: 'automation.view',
    defaultExpandedForRoles: ['AO', 'OM'],
    status: 'foundation',
  },
  {
    id: 'ai_copilot',
    name: 'AI Copilot',
    routePrefix: '/ai-copilot',
    navGroup: 'intelligence',
    icon: 'sparkles',
    visibilityPermission: 'ai_copilot.view',
    featureFlag: 'tbos.ai.copilot',
    defaultExpandedForRoles: ['AO', 'OM'],
    status: 'foundation',
  },
  {
    id: 'notifications',
    name: 'Notifications',
    routePrefix: '/notifications',
    navGroup: 'intelligence',
    icon: 'bell',
    visibilityPermission: 'notifications.view',
    defaultExpandedForRoles: ['AO', 'OM'],
    status: 'foundation',
  },
  {
    id: 'knowledge',
    name: 'Knowledge',
    routePrefix: '/knowledge',
    navGroup: 'intelligence',
    icon: 'book-open',
    visibilityPermission: 'knowledge.view',
    defaultExpandedForRoles: ['AO', 'OM'],
    status: 'foundation',
  },
  {
    id: 'settings',
    name: 'Settings',
    routePrefix: '/settings',
    navGroup: 'intelligence',
    icon: 'settings',
    visibilityPermission: 'settings.profile.edit',
    defaultExpandedForRoles: ['AO', 'OM'],
    status: 'foundation',
  },

  {
    id: 'platform_console',
    name: 'Platform Console',
    routePrefix: '/console',
    navGroup: 'platform-console',
    icon: 'shield',
    visibilityPermission: 'platform_console.access',
    defaultExpandedForRoles: ['ADM'],
    status: 'foundation',
  },
];

export const MODULE_MAP: Record<string, ModuleDefinition> = Object.fromEntries(MODULE_REGISTRY.map((m) => [m.id, m]));
