import type { ComponentRegistryEntry } from '@/types/component-registry';

/**
 * The Component Library's source of truth — master prompt §6/§44. Covers
 * every reusable component in the app, both built this phase and inherited
 * from the Frontend Foundation (Button, RailNav, CommandPalette, etc.) so the
 * registry is complete, not just a list of what's new. `sourceDocuments` and
 * `screenIds` are cross-checked by validateComponentRegistry.ts against
 * PERMISSION_REGISTRY-style invariants: no duplicate IDs, no duplicate names,
 * no screen ID that doesn't exist in SCREEN_REGISTRY.
 */
export const COMPONENT_REGISTRY: ComponentRegistryEntry[] = [
  // ============================================================
  // LEVEL 1 — PRIMITIVES
  // ============================================================
  {
    componentId: 'TBOS-CMP-ACTION-002',
    name: 'Button',
    level: 'primitive',
    category: 'action',
    description: 'Primary/secondary/danger/ghost action trigger, 2 sizes.',
    sourceDocuments: ['design-system/12_COMPONENT_GUIDELINES.md'],
    screenIds: [],
    states: ['default', 'hover', 'active', 'disabled'],
    responsiveBehavior: { desktop: 'inline', tablet: 'inline', mobile: 'min 44px touch target' },
    accessibilityRequirements: ['real <button>', 'focus-visible ring', '44px touch target'],
    rtlBehavior: 'Icon+label gap uses logical spacing; no mirroring needed.',
    darkModeBehavior: 'Resolves via action.* semantic tokens — no component-level dark override.',
    status: 'ready',
    filePath: 'components/ui/Button.tsx',
  },
  {
    componentId: 'TBOS-CMP-ACTION-003',
    name: 'IconButton',
    level: 'primitive',
    category: 'action',
    description: 'Icon-only control with a mandatory accessible label.',
    sourceDocuments: ['design-system/08_ICONOGRAPHY.md §4'],
    screenIds: [],
    states: ['default', 'hover', 'active', 'disabled'],
    responsiveBehavior: { desktop: '44px hit area', tablet: '44px hit area', mobile: '44px hit area' },
    accessibilityRequirements: ['aria-label required by TypeScript prop', '44px minimum hit area regardless of icon size'],
    rtlBehavior: 'Caller-supplied `rtl:rotate-180` for directional icons (chevrons); non-directional icons unaffected.',
    darkModeBehavior: 'icon.* semantic tokens.',
    status: 'ready',
    filePath: 'components/ui/IconButton.tsx',
  },
  {
    componentId: 'TBOS-CMP-FORM-001',
    name: 'Field',
    level: 'primitive',
    category: 'form',
    description: 'Label → control → helper/error text wrapper (render-prop child).',
    sourceDocuments: ['design-system/12_COMPONENT_GUIDELINES.md §3 Form Field'],
    screenIds: [],
    states: ['default', 'error', 'disabled', 'required'],
    responsiveBehavior: { desktop: 'stacked', tablet: 'stacked', mobile: 'stacked' },
    accessibilityRequirements: ['real <label htmlFor>', 'aria-describedby links hint/error', 'aria-invalid on error'],
    rtlBehavior: 'Logical text alignment; error asterisk uses text-start flow.',
    darkModeBehavior: 'text.*/border.danger tokens.',
    status: 'ready',
    filePath: 'components/ui/Field.tsx',
  },
  {
    componentId: 'TBOS-CMP-FORM-002',
    name: 'Input',
    level: 'primitive',
    category: 'form',
    description: 'Text input — default/error/disabled/read-only.',
    sourceDocuments: ['design-system/12_COMPONENT_GUIDELINES.md §3 Form Field'],
    screenIds: [],
    states: ['default', 'focus', 'error', 'disabled', 'readonly'],
    responsiveBehavior: { desktop: 'full width of field', tablet: 'full width of field', mobile: 'full width, 44px min height' },
    accessibilityRequirements: ['native <input>', 'focus-visible ring uses border.focus'],
    rtlBehavior: 'Logical padding (ps/pe); text direction inherits document dir.',
    darkModeBehavior: 'bg.surface/border tokens.',
    status: 'ready',
    filePath: 'components/ui/Input.tsx',
  },
  {
    componentId: 'TBOS-CMP-FORM-003',
    name: 'Textarea',
    level: 'primitive',
    category: 'form',
    description: 'Multi-line text input.',
    sourceDocuments: ['design-system/12_COMPONENT_GUIDELINES.md §3 Form Field'],
    screenIds: [],
    states: ['default', 'focus', 'error', 'disabled'],
    responsiveBehavior: { desktop: 'vertically resizable', tablet: 'vertically resizable', mobile: 'vertically resizable' },
    accessibilityRequirements: ['native <textarea>'],
    rtlBehavior: 'Logical padding; text direction inherits.',
    darkModeBehavior: 'bg.surface/border tokens.',
    status: 'ready',
    filePath: 'components/ui/Textarea.tsx',
  },
  {
    componentId: 'TBOS-CMP-FORM-004',
    name: 'Select',
    level: 'primitive',
    category: 'form',
    description: 'Native <select> with a design-token-styled chevron.',
    sourceDocuments: ['design-system/12_COMPONENT_GUIDELINES.md §3 Form Field'],
    screenIds: [],
    states: ['default', 'focus', 'error', 'disabled'],
    responsiveBehavior: { desktop: 'native platform dropdown', tablet: 'native platform dropdown', mobile: 'native OS picker' },
    accessibilityRequirements: ['native <select> — full keyboard/screen-reader support for free'],
    rtlBehavior: 'Chevron at logical end (`end-3`); native option text follows document dir.',
    darkModeBehavior: 'bg.surface/border tokens.',
    status: 'ready',
    filePath: 'components/ui/Select.tsx',
  },
  {
    componentId: 'TBOS-CMP-FORM-005',
    name: 'Checkbox',
    level: 'primitive',
    category: 'form',
    description: 'Real input[type=checkbox] under custom paint.',
    sourceDocuments: ['design-system/12_COMPONENT_GUIDELINES.md'],
    screenIds: [],
    states: ['default', 'checked', 'disabled'],
    responsiveBehavior: { desktop: '44px label hit area', tablet: '44px label hit area', mobile: '44px label hit area' },
    accessibilityRequirements: ['native input, never a styled div', 'label always associated via htmlFor'],
    rtlBehavior: 'Checkbox sits at logical start of label via normal inline flow.',
    darkModeBehavior: 'border-strong/bg-brand tokens.',
    status: 'ready',
    filePath: 'components/ui/Checkbox.tsx',
  },
  {
    componentId: 'TBOS-CMP-FORM-006',
    name: 'Radio',
    level: 'primitive',
    category: 'form',
    description: 'Real input[type=radio] under custom paint.',
    sourceDocuments: ['design-system/12_COMPONENT_GUIDELINES.md'],
    screenIds: [],
    states: ['default', 'checked', 'disabled'],
    responsiveBehavior: { desktop: '44px label hit area', tablet: '44px label hit area', mobile: '44px label hit area' },
    accessibilityRequirements: ['native input, never a styled div'],
    rtlBehavior: 'Normal inline flow.',
    darkModeBehavior: 'border-strong/bg-brand tokens.',
    status: 'ready',
    filePath: 'components/ui/Radio.tsx',
  },
  {
    componentId: 'TBOS-CMP-FORM-007',
    name: 'Switch',
    level: 'primitive',
    category: 'form',
    description: 'Toggle switch — saves immediately on change, no separate save button.',
    sourceDocuments: ['design-system/12_COMPONENT_GUIDELINES.md §3 Toggle Switch'],
    screenIds: ['NOTIF-02', 'AUTO-02'],
    states: ['on', 'off', 'disabled'],
    responsiveBehavior: { desktop: 'inline', tablet: 'inline', mobile: '44px hit area' },
    accessibilityRequirements: ['role="switch"', 'aria-checked'],
    rtlBehavior: 'Thumb translate direction flips via `rtl:` variant (transforms have no logical equivalent).',
    darkModeBehavior: 'bg.brand/bg.sunken tokens.',
    status: 'ready',
    filePath: 'components/ui/Switch.tsx',
  },
  {
    componentId: 'TBOS-CMP-STATUS-006',
    name: 'Badge',
    level: 'primitive',
    category: 'status',
    description: 'Generic tone-based pill — the non-lifecycle sibling of StatusBadge (e.g. priority tags, registry status chips).',
    sourceDocuments: ['design-system/12_COMPONENT_GUIDELINES.md'],
    screenIds: [],
    states: ['neutral', 'brand', 'success', 'warning', 'danger', 'info', 'ai'],
    responsiveBehavior: { desktop: 'inline', tablet: 'inline', mobile: 'inline' },
    accessibilityRequirements: ['always renders visible text, optional icon reinforces'],
    rtlBehavior: 'Icon+text gap logical.',
    darkModeBehavior: 'bg.*-subtle/text.* token pairs per tone.',
    status: 'ready',
    filePath: 'components/ui/Badge.tsx',
  },
  {
    componentId: 'TBOS-CMP-DISPLAY-001',
    name: 'Avatar',
    level: 'primitive',
    category: 'display',
    description: 'Initials or photo, 4 sizes.',
    sourceDocuments: ['design-system/tokens.json sizing.avatar'],
    screenIds: [],
    states: ['initials', 'image'],
    responsiveBehavior: { desktop: 'fixed size', tablet: 'fixed size', mobile: 'fixed size' },
    accessibilityRequirements: ['role="img" + aria-label on initials variant', 'alt text on image variant'],
    rtlBehavior: 'Never mirrors (a face/initial has no directionality) — design-system/08_ICONOGRAPHY.md §6 principle extended.',
    darkModeBehavior: 'bg.brand-subtle/text.brand tokens.',
    status: 'ready',
    filePath: 'components/ui/Avatar.tsx',
  },
  {
    componentId: 'TBOS-CMP-DISPLAY-002',
    name: 'Divider',
    level: 'primitive',
    category: 'display',
    description: 'Horizontal or vertical hairline separator.',
    sourceDocuments: ['design-system/09_ELEVATION_SYSTEM.md §5'],
    screenIds: [],
    states: [],
    responsiveBehavior: { desktop: 'n/a', tablet: 'n/a', mobile: 'n/a' },
    accessibilityRequirements: ['role="separator"', 'aria-orientation'],
    rtlBehavior: 'No directional concern — a line has no direction.',
    darkModeBehavior: 'border token.',
    status: 'ready',
    filePath: 'components/ui/Divider.tsx',
  },
  {
    componentId: 'TBOS-CMP-DISPLAY-003',
    name: 'Progress',
    level: 'primitive',
    category: 'display',
    description: 'Determinate progress bar, tone-driven fill color.',
    sourceDocuments: ['design-system/12_COMPONENT_GUIDELINES.md §6 Quota/Balance Meter'],
    screenIds: ['WAL-01'],
    states: ['brand', 'success', 'warning', 'danger'],
    responsiveBehavior: { desktop: 'full width of container', tablet: 'full width', mobile: 'full width' },
    accessibilityRequirements: ['role="progressbar"', 'aria-valuenow/min/max', 'aria-label states the meaning, not just the number'],
    rtlBehavior: 'Fill grows from logical start — a percentage-width div respects document dir automatically.',
    darkModeBehavior: 'bg.sunken track + chart.status-* fill tokens.',
    status: 'ready',
    filePath: 'components/ui/Progress.tsx',
  },
  {
    componentId: 'TBOS-CMP-DISPLAY-004',
    name: 'Tabs',
    level: 'primitive',
    category: 'display',
    description: 'Tab Group — also serves the EntityDetailTabs role for *-02 detail screens (no separate wrapper built; see report "Known Limitations" for this consolidation).',
    sourceDocuments: ['design-system/12_COMPONENT_GUIDELINES.md §1 Tab Group'],
    screenIds: ['PROP-02', 'PROJ-02', 'CONT-02', 'SET-02', 'AICP-02'],
    states: ['default', 'active', 'disabled'],
    responsiveBehavior: { desktop: 'horizontal row', tablet: 'horizontal row', mobile: 'horizontal row, scrollable if overflow (select-style fallback for >4 tabs deferred, see report)' },
    accessibilityRequirements: ['role=tablist/tab/tabpanel', 'arrow-key navigation', 'aria-selected', 'disabled tab keeps a stated reason'],
    rtlBehavior: 'Arrow-key direction is logical (ArrowRight always advances) — tab order follows document flow.',
    darkModeBehavior: 'border-brand/text-brand active-state tokens.',
    status: 'ready',
    filePath: 'components/ui/Tabs.tsx',
  },
  {
    componentId: 'TBOS-CMP-DISPLAY-005',
    name: 'Icon',
    level: 'primitive',
    category: 'display',
    description: 'The hand-authored 24×24 stroke icon set (design-system/08_ICONOGRAPHY.md grammar).',
    sourceDocuments: ['design-system/08_ICONOGRAPHY.md'],
    screenIds: [],
    states: [],
    responsiveBehavior: { desktop: 'sm/md/lg/xl per icon-to-text pairing table', tablet: 'same', mobile: 'same' },
    accessibilityRequirements: ['aria-hidden by default (decorative); consumer adds a label when the icon is the only content'],
    rtlBehavior: 'Each icon is classified directional/non-directional at the call site via rtl:rotate-180 — no built-in auto-mirroring.',
    darkModeBehavior: 'currentColor — inherits icon.* token from parent.',
    status: 'ready',
    filePath: 'components/ui/Icon.tsx',
  },
  {
    componentId: 'TBOS-CMP-DISPLAY-006',
    name: 'Skeleton',
    level: 'primitive',
    category: 'display',
    description: 'Shape-matched loading placeholder.',
    sourceDocuments: ['design-system/12_COMPONENT_GUIDELINES.md §4 Skeleton Loader'],
    screenIds: [],
    states: ['loading'],
    responsiveBehavior: { desktop: 'caller-sized', tablet: 'caller-sized', mobile: 'caller-sized' },
    accessibilityRequirements: ['role="presentation"', 'respects prefers-reduced-motion (pulse collapses to static opacity)'],
    rtlBehavior: 'No directional concern.',
    darkModeBehavior: 'bg.sunken token.',
    status: 'ready',
    filePath: 'components/ui/Skeleton.tsx',
  },
  {
    componentId: 'TBOS-CMP-DISPLAY-007',
    name: 'Spinner',
    level: 'primitive',
    category: 'display',
    description: 'Indeterminate loading indicator — used only where content shape is unknown (Skeleton is preferred otherwise, master prompt §35).',
    sourceDocuments: ['design-system/12_COMPONENT_GUIDELINES.md'],
    screenIds: [],
    states: ['loading'],
    responsiveBehavior: { desktop: 'caller-sized', tablet: 'caller-sized', mobile: 'caller-sized' },
    accessibilityRequirements: ['role="status"', 'aria-label', 'motion-reduce:animate-none'],
    rtlBehavior: 'No directional concern.',
    darkModeBehavior: 'border token.',
    status: 'ready',
    filePath: 'components/ui/Spinner.tsx',
  },
  {
    componentId: 'TBOS-CMP-DISPLAY-008',
    name: 'TubaLogo',
    level: 'tbos',
    category: 'display',
    description: 'The official Tuba logo, traced (not redrawn) from public/ar-color-TubaLogo2.svg and public/en_coloredLogo.svg, locale-switched automatically. Wordmark uses currentColor (text.brand light / white dark); house mark is the fixed --tuba-coral token in both.',
    sourceDocuments: ['public/ar-color-TubaLogo2.svg', 'public/en_coloredLogo.svg', 'design-system/03_COLOR_SYSTEM.md §1a'],
    screenIds: [],
    states: ['ar', 'en'],
    responsiveBehavior: { desktop: 'fixed height, intrinsic aspect ratio', tablet: 'same', mobile: 'same' },
    accessibilityRequirements: ['role="img" with a translated aria-label (app.name), never unlabeled decorative markup'],
    rtlBehavior: 'Never mirrors — a wordmark has no directionality (design-system/08_ICONOGRAPHY.md §6 principle extended); the Arabic and Latin variants are two distinct authored assets, not one mechanically flipped.',
    darkModeBehavior: 'Wordmark: text.brand (light) / white (dark, explicit user preference — see TBOS_UI_VERTICAL_SLICE_REPORT.md logo addendum). House mark: --tuba-coral, unchanged in both themes.',
    status: 'ready',
    filePath: 'components/brand/TubaLogo.tsx',
  },
  {
    componentId: 'TBOS-CMP-OVERLAY-001',
    name: 'Tooltip',
    level: 'primitive',
    category: 'overlay',
    description: 'Non-interactive supplementary text, hover + keyboard focus trigger.',
    sourceDocuments: ['design-system/12_COMPONENT_GUIDELINES.md §1'],
    screenIds: [],
    states: ['visible', 'hidden'],
    responsiveBehavior: { desktop: 'hover or focus', tablet: 'focus (no hover)', mobile: 'focus only' },
    accessibilityRequirements: ['role="tooltip"', 'shows on focus, not just hover'],
    rtlBehavior: 'Centered via translate + explicit rtl: variant override (documented exception — transforms have no logical property).',
    darkModeBehavior: 'Fixed dark slate surface regardless of theme (tooltips read as an overlay in both modes).',
    status: 'ready',
    filePath: 'components/ui/Tooltip.tsx',
  },
  {
    componentId: 'TBOS-CMP-OVERLAY-002',
    name: 'Popover',
    level: 'primitive',
    category: 'overlay',
    description: 'Generic click-triggered floating panel for interactive content.',
    sourceDocuments: ['design-system/09_ELEVATION_SYSTEM.md §1/§6 (elevation.2, zIndex.popover)'],
    screenIds: [],
    states: ['open', 'closed'],
    responsiveBehavior: { desktop: 'anchored to trigger', tablet: 'anchored to trigger', mobile: 'anchored to trigger (may overflow on very narrow viewports — caller constrains width)' },
    accessibilityRequirements: ['focus-trapped', 'Escape closes + restores focus (lib/a11y/useFocusTrap.ts)'],
    rtlBehavior: 'align="start"/"end" are logical, not left/right.',
    darkModeBehavior: 'bg.surface/border tokens.',
    status: 'ready',
    filePath: 'components/ui/Popover.tsx',
  },
  {
    componentId: 'TBOS-CMP-OVERLAY-003',
    name: 'Dialog',
    level: 'primitive',
    category: 'overlay',
    description: 'Generic modal — standard or alertdialog variant.',
    sourceDocuments: ['design-system/09_ELEVATION_SYSTEM.md (elevation.4, radius.xl, zIndex.modal)', 'design-system/12_COMPONENT_GUIDELINES.md §4 Confirmation Dialog'],
    screenIds: [],
    states: ['open', 'closed'],
    responsiveBehavior: { desktop: 'centered, sm/md/lg max-width', tablet: 'centered', mobile: 'centered with viewport padding' },
    accessibilityRequirements: ['role=dialog/alertdialog', 'aria-modal', 'focus-trapped', 'Escape closes + restores focus'],
    rtlBehavior: 'Close button at logical end via IconButton; header row uses justify-between (direction-agnostic).',
    darkModeBehavior: 'bg.overlay-scrim + bg.surface tokens.',
    status: 'ready',
    filePath: 'components/ui/Dialog.tsx',
  },
  {
    componentId: 'TBOS-CMP-OVERLAY-004',
    name: 'Drawer',
    level: 'primitive',
    category: 'overlay',
    description: 'Slide-over Panel — enters from the inline-end edge, full-screen push on mobile.',
    sourceDocuments: ['tbos-blueprint/02_NAVIGATION_BLUEPRINT.md §5', 'design-system/12_COMPONENT_GUIDELINES.md §1 Slide-over Panel'],
    screenIds: ['PROP-02', 'LEAD-03', 'CUST-02', 'TASK-02'],
    states: ['open', 'closed'],
    responsiveBehavior: { desktop: 'sm/md/lg fixed width panel', tablet: 'sm/md/lg fixed width panel', mobile: 'full-screen push (w-full)' },
    accessibilityRequirements: ['focus-trapped', 'Escape closes + restores focus', '"Open full record" escape hatch'],
    rtlBehavior: 'Enters from `end-0` (logical) — mirrors correctly by construction, not a special-cased flip.',
    darkModeBehavior: 'bg.surface/border-inline-start tokens.',
    status: 'ready',
    filePath: 'components/ui/Drawer.tsx',
  },
  {
    componentId: 'TBOS-CMP-ACTION-001',
    name: 'Dropdown',
    level: 'primitive',
    category: 'action',
    description: 'Generic action menu — real role="menu"/"menuitem" with arrow-key navigation.',
    sourceDocuments: ['design-system/12_COMPONENT_GUIDELINES.md'],
    screenIds: [],
    states: ['open', 'closed'],
    responsiveBehavior: { desktop: 'anchored', tablet: 'anchored', mobile: 'anchored' },
    accessibilityRequirements: ['role=menu/menuitem', 'ArrowUp/ArrowDown navigation', 'focus-trapped'],
    rtlBehavior: 'align="start"/"end" logical.',
    darkModeBehavior: 'bg.surface/border tokens.',
    status: 'ready',
    filePath: 'components/ui/Dropdown.tsx',
  },
  {
    componentId: 'TBOS-CMP-FEEDBACK-001',
    name: 'Alert',
    level: 'primitive',
    category: 'feedback',
    description: 'Tone-driven inline/banner message — the Banner/Alert/InlineMessage primitive.',
    sourceDocuments: ['design-system/12_COMPONENT_GUIDELINES.md §4 Error Inline/Banner'],
    screenIds: [],
    states: ['neutral', 'info', 'warning', 'danger', 'success'],
    responsiveBehavior: { desktop: 'full width of container', tablet: 'full width', mobile: 'full width' },
    accessibilityRequirements: ['role=status by default; role=alert only when assertive=true (page/incident-level)'],
    rtlBehavior: 'Icon+content gap logical.',
    darkModeBehavior: 'bg.*-subtle/text.* per tone.',
    status: 'ready',
    filePath: 'components/ui/Alert.tsx',
  },

  // ============================================================
  // LEVEL 2 — TBOS COMPONENTS
  // ============================================================
  {
    componentId: 'TBOS-CMP-STATUS-001',
    name: 'StatusBadge',
    level: 'tbos',
    category: 'status',
    description: 'The one Status Badge every module lifecycle renders through — per-module state maps, five-meaning color system.',
    sourceDocuments: ['design-system/12_COMPONENT_GUIDELINES.md §2', 'design-system/03_COLOR_SYSTEM.md §3'],
    screenIds: ['PROP-01', 'PROP-02', 'LEAD-01', 'LEAD-03', 'CONT-01', 'CONT-02', 'OWN-03', 'MKT-01'],
    states: ['neutral', 'info', 'warning', 'success', 'danger'],
    responsiveBehavior: { desktop: 'inline pill', tablet: 'inline pill', mobile: 'inline pill' },
    accessibilityRequirements: ['icon + text always paired — never color alone'],
    rtlBehavior: 'Icon+text gap logical; pill shape unaffected by direction.',
    darkModeBehavior: 'bg.*-subtle/text.* per meaning.',
    status: 'ready',
    filePath: 'components/tbos/status/StatusBadge.tsx',
  },
  {
    componentId: 'TBOS-CMP-STATUS-002',
    name: 'LifecycleIndicator',
    level: 'tbos',
    category: 'status',
    description: 'Denser inline sibling to StatusBadge for timeline nodes / compact table cells.',
    sourceDocuments: ['design-system/12_COMPONENT_GUIDELINES.md §2'],
    screenIds: [],
    states: ['neutral', 'info', 'warning', 'success', 'danger'],
    responsiveBehavior: { desktop: 'inline', tablet: 'inline', mobile: 'inline' },
    accessibilityRequirements: ['text label always present; dot is aria-hidden reinforcement, not the sole signal'],
    rtlBehavior: 'Dot+label gap logical.',
    darkModeBehavior: 'Tailwind default palette dot colors (info-500 etc.) — same values light/dark by design (status colors are mode-invariant per design-system/14_DARK_MODE.md §4).',
    status: 'ready',
    filePath: 'components/tbos/status/LifecycleIndicator.tsx',
  },
  {
    componentId: 'TBOS-CMP-STATUS-003',
    name: 'LeadStageBadge',
    level: 'tbos',
    category: 'status',
    description: "StatusBadge fed Lead's 7-stage pipeline state map.",
    sourceDocuments: ['design-system/03_COLOR_SYSTEM.md §3 Lead pipeline table'],
    screenIds: ['LEAD-01', 'LEAD-02', 'LEAD-03'],
    states: ['new', 'assigned', 'contacted', 'qualified', 'negotiating', 'won', 'lost'],
    responsiveBehavior: { desktop: 'inline pill', tablet: 'inline pill', mobile: 'inline pill' },
    accessibilityRequirements: ['inherits StatusBadge'],
    rtlBehavior: 'inherits StatusBadge.',
    darkModeBehavior: 'inherits StatusBadge.',
    status: 'ready',
    filePath: 'components/tbos/lead/LeadStageBadge.tsx',
  },
  {
    componentId: 'TBOS-CMP-STATUS-004',
    name: 'PropertyStatusBadge',
    level: 'tbos',
    category: 'status',
    description: "StatusBadge fed Property's 8-state lifecycle map, including the Sold/Rented-vs-Active icon distinction.",
    sourceDocuments: ['design-system/03_COLOR_SYSTEM.md §3 Property/Project table'],
    screenIds: ['PROP-01', 'PROP-02', 'PROJ-01', 'PROJ-02'],
    states: ['draft', 'pending_compliance', 'active', 'expiring', 'expired', 'rejected', 'sold_rented', 'archived'],
    responsiveBehavior: { desktop: 'inline pill', tablet: 'inline pill', mobile: 'inline pill' },
    accessibilityRequirements: ['inherits StatusBadge'],
    rtlBehavior: 'inherits StatusBadge.',
    darkModeBehavior: 'inherits StatusBadge.',
    status: 'ready',
    filePath: 'components/tbos/status/PropertyStatusBadge.tsx',
  },
  {
    componentId: 'TBOS-CMP-STATUS-005',
    name: 'ContractStatusBadge',
    level: 'tbos',
    category: 'status',
    description: "StatusBadge fed Contract's 6-state lifecycle map.",
    sourceDocuments: ['design-system/03_COLOR_SYSTEM.md §3 Contract table'],
    screenIds: ['CONT-01', 'CONT-02'],
    states: ['draft', 'pending_compliance', 'active', 'renewal_due', 'closed', 'cancelled'],
    responsiveBehavior: { desktop: 'inline pill', tablet: 'inline pill', mobile: 'inline pill' },
    accessibilityRequirements: ['inherits StatusBadge'],
    rtlBehavior: 'inherits StatusBadge.',
    darkModeBehavior: 'inherits StatusBadge.',
    status: 'ready',
    filePath: 'components/tbos/status/ContractStatusBadge.tsx',
  },
  {
    componentId: 'TBOS-CMP-STATUS-007',
    name: 'SlaTimer',
    level: 'tbos',
    category: 'status',
    description: 'The SLA Timer — countdown urgency badge for a lead approaching/past its SLA window. Previously unbuilt (TBOS_UI_INTEGRATION_AUDIT.md §1.E); reuses StatusBadge rather than a bespoke shape.',
    sourceDocuments: ['tbos-blueprint/05_COMPONENT_MAPPING.md'],
    screenIds: ['TODAY-01', 'LEAD-01', 'LEAD-02', 'LEAD-03'],
    states: ['healthy', 'approaching', 'breaching', 'none'],
    responsiveBehavior: { desktop: 'inline pill', tablet: 'inline pill', mobile: 'inline pill' },
    accessibilityRequirements: ['inherits StatusBadge — icon + text always paired'],
    rtlBehavior: 'inherits StatusBadge.',
    darkModeBehavior: 'inherits StatusBadge.',
    status: 'ready',
    filePath: 'components/tbos/lead/SlaTimer.tsx',
  },
  {
    componentId: 'TBOS-CMP-STATUS-008',
    name: 'AdvertisementStatusBadge',
    level: 'tbos',
    category: 'status',
    description:
      "StatusBadge fed the property's REGA Ad License compliance status, deliberately separate from PropertyStatusBadge/PromotionBadge (TBOS_MY_PROPERTIES_UX_ARCHITECTURE.md Part 05: never merge Property/Advertisement/Promotion into one badge).",
    sourceDocuments: ['TBOS_MY_PROPERTIES_UX_ARCHITECTURE.md Part 05', 'TBOS_MY_PROPERTIES_AUDIT.md §6.1'],
    screenIds: ['PROP-01'],
    states: ['verified', 'pending_verification', 'expiring', 'expired', 'missing', 'none'],
    responsiveBehavior: { desktop: 'inline pill', tablet: 'inline pill', mobile: 'inline pill' },
    accessibilityRequirements: ['inherits StatusBadge'],
    rtlBehavior: 'inherits StatusBadge.',
    darkModeBehavior: 'inherits StatusBadge.',
    status: 'ready',
    filePath: 'components/tbos/status/AdvertisementStatusBadge.tsx',
  },
  {
    componentId: 'TBOS-CMP-STATUS-009',
    name: 'PromotionBadge',
    level: 'tbos',
    category: 'status',
    description: 'Featured/Pro promotion tier tag — renders nothing for Basic (the default) to avoid always-on badge clutter across the list.',
    sourceDocuments: ['TBOS_MY_PROPERTIES_UX_ARCHITECTURE.md §6 (Decision 04)'],
    screenIds: ['PROP-01'],
    states: ['featured', 'pro'],
    responsiveBehavior: { desktop: 'inline pill', tablet: 'inline pill', mobile: 'inline pill' },
    accessibilityRequirements: ['text label always present, never color/icon alone'],
    rtlBehavior: 'Icon+text gap logical.',
    darkModeBehavior: 'bg-bg-brand-subtle/text-text-brand — same tokens light/dark.',
    status: 'ready',
    filePath: 'components/tbos/status/PromotionBadge.tsx',
  },
  {
    componentId: 'TBOS-CMP-DATA-001',
    name: 'MetricCard',
    level: 'tbos',
    category: 'data',
    description: 'The Metric Tile — label, value, delta, as-of timestamp, loading/error per-tile degradation.',
    sourceDocuments: ['design-system/12_COMPONENT_GUIDELINES.md §2 Metric Tile'],
    screenIds: ['HOME-01', 'TODAY-01', 'ANL-01', 'WAL-01'],
    states: ['loading', 'error', 'success'],
    responsiveBehavior: { desktop: '4–6 per row (grid, caller-controlled)', tablet: '4 per row', mobile: '2 per row' },
    accessibilityRequirements: ['aria-label states the metric\'s plain-language meaning, not just its number', 'landmark region'],
    rtlBehavior: 'Delta icon direction (up/down) is vertical, not mirrored; layout uses logical flex.',
    darkModeBehavior: 'bg.surface/border tokens; chart.status-* delta colors are mode-invariant.',
    status: 'ready',
    filePath: 'components/tbos/data/MetricCard.tsx',
  },
  {
    componentId: 'TBOS-CMP-DATA-002',
    name: 'MetricWithExplanation',
    level: 'tbos',
    category: 'data',
    description: 'MetricCard pre-wired with an ExplainabilityPopover trigger — the Decision Support System\'s "no bare number" rule made structural.',
    sourceDocuments: ['tbos-blueprint/07_DECISION_SUPPORT_SYSTEM.md'],
    screenIds: ['HOME-01', 'TODAY-01', 'ANL-01'],
    states: ['loading', 'error', 'success'],
    permissions: [],
    responsiveBehavior: { desktop: 'inherits MetricCard', tablet: 'inherits MetricCard', mobile: 'inherits MetricCard' },
    accessibilityRequirements: ['inherits MetricCard + ExplainabilityPopover'],
    rtlBehavior: 'inherits MetricCard + ExplainabilityPopover.',
    darkModeBehavior: 'inherits MetricCard + ExplainabilityPopover.',
    status: 'ready',
    filePath: 'components/tbos/data/MetricWithExplanation.tsx',
  },
  {
    componentId: 'TBOS-CMP-DATA-003',
    name: 'QuotaBalanceMeter',
    level: 'tbos',
    category: 'data',
    description: 'Wallet quota/credit usage bar — current/limit always stated as text, tone shifts Success→Warning→Danger.',
    sourceDocuments: ['design-system/12_COMPONENT_GUIDELINES.md §6'],
    screenIds: ['WAL-01', 'HOME-01', 'MKT-02'],
    states: ['success', 'warning', 'danger'],
    responsiveBehavior: { desktop: 'full width of container', tablet: 'full width', mobile: 'full width' },
    accessibilityRequirements: ['inherits Progress'],
    rtlBehavior: 'inherits Progress.',
    darkModeBehavior: 'inherits Progress.',
    status: 'ready',
    filePath: 'components/tbos/data/QuotaBalanceMeter.tsx',
  },
  {
    componentId: 'TBOS-CMP-DATA-005',
    name: 'PropertyPerformanceSummary',
    level: 'tbos',
    category: 'data',
    description:
      "PROP-01's quick performance summary — real Leads count (computed from Lead↔Property links) plus an honest 'not tracked yet' state for Reach/Views, which have no real data source anywhere in TBOS today. Open-ended metric slots, future-ready without a redesign (TBOS_MY_PROPERTIES_UX_ARCHITECTURE.md §8).",
    sourceDocuments: ['TBOS_MY_PROPERTIES_UX_ARCHITECTURE.md §8', 'TBOS_MY_PROPERTIES_STATE_MATRIX.md §8.4'],
    screenIds: ['PROP-01'],
    states: ['success', 'not-tracked'],
    responsiveBehavior: { desktop: 'inline row', tablet: 'inline row', mobile: 'inline row' },
    accessibilityRequirements: ["each metric carries an aria-label pairing its name with its value or 'not tracked yet' state — never a bare icon+number"],
    rtlBehavior: 'Icon+text gap logical; row order follows reading direction.',
    darkModeBehavior: 'text-text-secondary/text-text-muted — same tokens light/dark.',
    status: 'ready',
    filePath: 'components/tbos/data/PropertyPerformanceSummary.tsx',
  },
  {
    componentId: 'TBOS-CMP-ENTITY-001',
    name: 'EntityAvatar',
    level: 'tbos',
    category: 'entity',
    description: 'Person entities get initials (Avatar); record entities (Property/Contract/Campaign) get a type icon in the same footprint.',
    sourceDocuments: ['master prompt §16 "composable entity primitives"'],
    screenIds: [],
    states: ['person', 'record'],
    responsiveBehavior: { desktop: 'fixed size', tablet: 'fixed size', mobile: 'fixed size' },
    accessibilityRequirements: ['inherits Avatar for person kind; record kind icon is decorative (aria-hidden via Icon)'],
    rtlBehavior: 'Never mirrors.',
    darkModeBehavior: 'bg.brand-subtle/text.brand tokens.',
    status: 'ready',
    filePath: 'components/tbos/entity/EntityAvatar.tsx',
  },
  {
    componentId: 'TBOS-CMP-ENTITY-002',
    name: 'EntityMeta',
    level: 'tbos',
    category: 'entity',
    description: 'Icon+text meta row under an entity title (district, price, due date, linked-record count).',
    sourceDocuments: ['design-system/12_COMPONENT_GUIDELINES.md §2 Detail Header'],
    screenIds: [],
    states: [],
    responsiveBehavior: { desktop: 'flex-wrap row', tablet: 'flex-wrap row', mobile: 'flex-wrap row' },
    accessibilityRequirements: ['real <ul>/<li> list, icons aria-hidden, text carries meaning'],
    rtlBehavior: 'Logical gap; wraps naturally in either direction.',
    darkModeBehavior: 'text.secondary/icon.muted tokens.',
    status: 'ready',
    filePath: 'components/tbos/entity/EntityMeta.tsx',
  },
  {
    componentId: 'TBOS-CMP-ENTITY-003',
    name: 'EntityCard',
    level: 'tbos',
    category: 'entity',
    description: 'One composable card for every entity type — deliberately not a PropertyCard/LeadCard/CustomerCard per module (master prompt §16/§38 anti-proliferation).',
    sourceDocuments: ['master prompt §16, §38'],
    screenIds: [],
    states: ['static', 'interactive'],
    responsiveBehavior: { desktop: 'fixed card', tablet: 'fixed card', mobile: 'full width card' },
    accessibilityRequirements: ['renders as <button> when interactive (onClick supplied), <div> otherwise — never a div with a bare click handler'],
    rtlBehavior: 'text-start title/subtitle; composes EntityAvatar/EntityMeta which are already RTL-correct.',
    darkModeBehavior: 'bg.surface/border tokens.',
    status: 'ready',
    filePath: 'components/tbos/entity/EntityCard.tsx',
  },
  {
    componentId: 'TBOS-CMP-PERMISSION-001',
    name: 'PermissionGate',
    level: 'tbos',
    category: 'permission',
    description: "Wraps lib/permissions/useHasPermission() — hide or disable-with-reason. Never a second authorization implementation.",
    sourceDocuments: ['RBAC.md', 'master prompt §28/§51'],
    screenIds: [],
    states: ['allowed', 'hidden', 'disabled'],
    permissions: ['(caller-supplied permission key)'],
    responsiveBehavior: { desktop: 'no layout impact', tablet: 'no layout impact', mobile: 'no layout impact' },
    accessibilityRequirements: ['disable mode sets aria-disabled + a Tooltip explaining why, never a silently-vanished control the user expected'],
    rtlBehavior: 'No directional concern — pass-through wrapper.',
    darkModeBehavior: 'No visual output of its own.',
    status: 'ready',
    filePath: 'components/tbos/permissions/PermissionGate.tsx',
  },
  {
    componentId: 'TBOS-CMP-COMPLIANCE-001',
    name: 'ComplianceStatus',
    level: 'tbos',
    category: 'compliance',
    description: 'StatusBadge fed a compliance-specific state map — deliberately no dedicated compliance hue.',
    sourceDocuments: ['design-system/03_COLOR_SYSTEM.md §4'],
    screenIds: ['SET-04', 'CONT-02'],
    states: ['not_started', 'pending_verification', 'verified', 'expiring', 'expired', 'mismatch'],
    responsiveBehavior: { desktop: 'inline pill', tablet: 'inline pill', mobile: 'inline pill' },
    accessibilityRequirements: ['inherits StatusBadge'],
    rtlBehavior: 'inherits StatusBadge.',
    darkModeBehavior: 'inherits StatusBadge.',
    status: 'ready',
    filePath: 'components/tbos/compliance/ComplianceStatus.tsx',
  },
  {
    componentId: 'TBOS-CMP-COMPLIANCE-002',
    name: 'ComplianceExpiry',
    level: 'tbos',
    category: 'compliance',
    description: 'Proximity-aware urgency display for a license/document deadline.',
    sourceDocuments: ['tbos-blueprint/09_NOTIFICATION_BLUEPRINT.md reminder model'],
    screenIds: ['SET-04'],
    states: ['far', 'approaching', 'urgent'],
    responsiveBehavior: { desktop: 'inline', tablet: 'inline', mobile: 'inline' },
    accessibilityRequirements: ['text label carries the deadline meaning, color is reinforcement'],
    rtlBehavior: 'Icon+text gap logical.',
    darkModeBehavior: 'text.danger/text.warning/text.secondary tokens.',
    status: 'ready',
    filePath: 'components/tbos/compliance/ComplianceExpiry.tsx',
  },
  {
    componentId: 'TBOS-CMP-COMPLIANCE-003',
    name: 'ComplianceChecklist',
    level: 'tbos',
    category: 'compliance',
    description: 'Ordered list of requirement rows, each plain-language, front-loaded — never a bare checkbox.',
    sourceDocuments: ['design-system/12_COMPONENT_GUIDELINES.md §3', 'tbos-definition/20_NON_GOALS.md #9'],
    screenIds: ['PROP-03', 'CONT-02', 'SET-04'],
    states: ['incomplete', 'complete', 'blocked'],
    responsiveBehavior: { desktop: 'stacked list', tablet: 'stacked list', mobile: 'stacked list' },
    accessibilityRequirements: ['real <ol role="list">', 'per-item checked-state announced via visible + sr-only text'],
    rtlBehavior: 'Icon+text row uses logical gap.',
    darkModeBehavior: 'text.success/text.danger/icon.muted tokens.',
    status: 'ready',
    filePath: 'components/tbos/compliance/ComplianceChecklist.tsx',
  },
  {
    componentId: 'TBOS-CMP-COMPLIANCE-004',
    name: 'ComplianceDocument',
    level: 'tbos',
    category: 'compliance',
    description: 'A single uploaded document row — filename, status, action.',
    sourceDocuments: ['tbos-blueprint/04_SCREEN_INVENTORY.md SET-04'],
    screenIds: ['SET-04', 'CONT-02'],
    states: ['not_started', 'pending_verification', 'verified', 'expiring', 'expired', 'mismatch'],
    responsiveBehavior: { desktop: 'row', tablet: 'row', mobile: 'row, truncates filename' },
    accessibilityRequirements: ['filename truncates visually but remains in the accessible name (title attribute recommended for callers)'],
    rtlBehavior: 'Icon at logical start, status+action at logical end.',
    darkModeBehavior: 'border/icon.muted tokens.',
    status: 'ready',
    filePath: 'components/tbos/compliance/ComplianceDocument.tsx',
  },
  {
    componentId: 'TBOS-CMP-NOTIFICATION-001',
    name: 'NotificationItem',
    level: 'tbos',
    category: 'notification',
    description: 'The Notification List Item — urgency badge, message, unread state. Consumed by NotificationBell today; NOTIF-01 reuses unchanged.',
    sourceDocuments: ['design-system/12_COMPONENT_GUIDELINES.md §6'],
    screenIds: ['NOTIF-01'],
    states: ['read', 'unread'],
    responsiveBehavior: { desktop: 'row in dropdown/list', tablet: 'row', mobile: 'row, full width' },
    accessibilityRequirements: ['real <button>', 'priority badge text-visible, never color-only'],
    rtlBehavior: 'text-start; badge at logical end via flex.',
    darkModeBehavior: 'bg.brand-subtle unread state token.',
    status: 'ready',
    filePath: 'components/tbos/notifications/NotificationItem.tsx',
  },
  {
    componentId: 'TBOS-CMP-AI-001',
    name: 'AIConfidence',
    level: 'tbos',
    category: 'ai',
    description: 'The Confidence Indicator — text label + icon, always visible, never hover-only or color-only.',
    sourceDocuments: ['design-system/12_COMPONENT_GUIDELINES.md §5 Confidence Indicator'],
    screenIds: ['AICP-01', 'LEAD-03'],
    states: ['high', 'medium', 'low'],
    responsiveBehavior: { desktop: 'inline', tablet: 'inline', mobile: 'inline' },
    accessibilityRequirements: ['text label always rendered, never hidden behind hover'],
    rtlBehavior: 'Icon+text gap logical.',
    darkModeBehavior: 'text.success/warning/danger tokens.',
    status: 'ready',
    filePath: 'components/tbos/ai/AIConfidence.tsx',
  },
  {
    componentId: 'TBOS-CMP-AI-002',
    name: 'AISourceTag',
    level: 'tbos',
    category: 'ai',
    description: 'Cites an AI output\'s grounding source.',
    sourceDocuments: ['tbos-blueprint/08_AI_INTERACTION_BLUEPRINT.md'],
    screenIds: ['AICP-01'],
    states: [],
    responsiveBehavior: { desktop: 'inline', tablet: 'inline', mobile: 'inline' },
    accessibilityRequirements: ['text-based, no icon-only variant'],
    rtlBehavior: 'Icon+text gap logical.',
    darkModeBehavior: 'text.muted token.',
    status: 'ready',
    filePath: 'components/tbos/ai/AISourceTag.tsx',
  },
  {
    componentId: 'TBOS-CMP-AI-003',
    name: 'AIActionBar',
    level: 'tbos',
    category: 'ai',
    description: 'Accept/Regenerate/Discard row — no AI action beyond read/answer executes without this bar\'s explicit accept.',
    sourceDocuments: ['tbos-blueprint/08_AI_INTERACTION_BLUEPRINT.md Agent Copilot'],
    screenIds: ['AICP-01'],
    states: [],
    responsiveBehavior: { desktop: 'row', tablet: 'row', mobile: 'row, may wrap' },
    accessibilityRequirements: ['inherits Button'],
    rtlBehavior: 'Button order follows logical flex — no manual reversal needed.',
    darkModeBehavior: 'inherits Button.',
    status: 'ready',
    filePath: 'components/tbos/ai/AIActionBar.tsx',
  },
  {
    componentId: 'TBOS-CMP-AI-004',
    name: 'AISuggestion',
    level: 'tbos',
    category: 'ai',
    description: 'The AI Suggestion Inline Block — Copilot-violet left accent, "AI suggested" label, editable content, confidence.',
    sourceDocuments: ['design-system/12_COMPONENT_GUIDELINES.md §5'],
    screenIds: ['PROP-03', 'MKT-02', 'LEAD-03'],
    states: ['pending_review', 'accepted', 'accepted_edited', 'discarded'],
    responsiveBehavior: { desktop: 'block', tablet: 'block', mobile: 'block' },
    accessibilityRequirements: ['content region marked as AI-suggested, never silently pre-filled as human-authored'],
    rtlBehavior: '4px accent border uses `border-s-4` (logical inline-start) — moves to the correct edge automatically in RTL.',
    darkModeBehavior: 'bg.ai-subtle/text.ai tokens (Copilot family — dark-mode-selected, not inverted).',
    status: 'ready',
    filePath: 'components/tbos/ai/AISuggestion.tsx',
  },
  {
    componentId: 'TBOS-CMP-AI-005',
    name: 'AIInsight',
    level: 'tbos',
    category: 'ai',
    description: 'One-to-two sentence plain-language AI narrative beside a metric — passive, no accept/reject.',
    sourceDocuments: ['tbos-blueprint/08_AI_INTERACTION_BLUEPRINT.md AI Insights'],
    screenIds: ['HOME-01', 'ANL-01'],
    states: [],
    responsiveBehavior: { desktop: 'inline with metric', tablet: 'inline', mobile: 'wraps below metric' },
    accessibilityRequirements: ['plain text, no interactive element required'],
    rtlBehavior: 'Icon+text gap logical.',
    darkModeBehavior: 'text.ai token.',
    status: 'ready',
    filePath: 'components/tbos/ai/AIInsight.tsx',
  },
  {
    componentId: 'TBOS-CMP-AI-006',
    name: 'AIConversationThread',
    level: 'tbos',
    category: 'ai',
    description: "AICP-01's conversation surface — AI messages carry the Copilot accent, user messages plain.",
    sourceDocuments: ['design-system/12_COMPONENT_GUIDELINES.md §5 AI Conversation Thread'],
    screenIds: ['AICP-01'],
    states: [],
    responsiveBehavior: { desktop: 'max-w-md bubbles', tablet: 'max-w-md bubbles', mobile: 'wider bubbles, same layout' },
    accessibilityRequirements: ['aria-live="polite" announces new messages on arrival, not per-character'],
    rtlBehavior: 'flex-row-reverse for user messages is logical-direction-aware (reverses again automatically under dir=rtl since flex-row-reverse is relative to inline axis).',
    darkModeBehavior: 'bg.ai-subtle/bg.brand-subtle bubble tokens.',
    status: 'ready',
    filePath: 'components/tbos/ai/AIConversationThread.tsx',
  },
  {
    componentId: 'TBOS-CMP-AI-007',
    name: 'RecommendationCard',
    level: 'tbos',
    category: 'ai',
    description: 'TODAY-01\'s one entry format — one action, its reasoning, its urgency, satisfying the Explainability contract on demand. Previously unbuilt (TBOS_UI_INTEGRATION_AUDIT.md §1.E).',
    sourceDocuments: ['tbos-blueprint/05_COMPONENT_MAPPING.md', 'tbos-blueprint/07_DECISION_SUPPORT_SYSTEM.md'],
    screenIds: ['TODAY-01'],
    states: ['critical', 'high', 'medium', 'low'],
    responsiveBehavior: { desktop: 'card in a vertical stack', tablet: 'card in a vertical stack', mobile: 'full-width card' },
    accessibilityRequirements: ['priority conveyed via StatusBadge (icon + text), never color-only', 'dismiss is a real labeled IconButton'],
    rtlBehavior: 'border-s-4 accent (logical) — sits on the correct edge in RTL automatically; inherits ExplainabilityPopover for its popover.',
    darkModeBehavior: 'bg.surface + text.{danger,warning,info} tokens for the priority accent — no hardcoded colors.',
    status: 'ready',
    filePath: 'components/tbos/ai/RecommendationCard.tsx',
  },
  {
    componentId: 'TBOS-CMP-EXPLAINABILITY-001',
    name: 'ExplainabilityPopover',
    level: 'tbos',
    category: 'explainability',
    description: 'The five-question contract (Why/How calculated/What changed/Recommended action/Business impact) on any metric, score, or AI output.',
    sourceDocuments: ['tbos-definition/14_EXPLAINABILITY_SYSTEM.md', 'design-system/12_COMPONENT_GUIDELINES.md §5'],
    screenIds: ['AICP-01', 'HOME-01', 'TODAY-01', 'ANL-01'],
    states: ['open', 'closed'],
    responsiveBehavior: { desktop: 'anchored popover', tablet: 'anchored popover', mobile: 'anchored popover (may need caller-side repositioning on very narrow viewports — deferred)' },
    accessibilityRequirements: ['triggered by a real button, never hover-only', 'focus-trapped'],
    rtlBehavior: 'start-0 anchor (logical).',
    darkModeBehavior: 'bg.surface/border tokens.',
    status: 'ready',
    filePath: 'components/ai/ExplainabilityPopover.tsx',
  },
  {
    componentId: 'TBOS-CMP-ACTIVITY-001',
    name: 'ActivityItem',
    level: 'tbos',
    category: 'activity',
    description: 'One timeline node — Human/System/AI actors stay semantically distinguishable by icon.',
    sourceDocuments: ['master prompt §22'],
    screenIds: [],
    states: [],
    responsiveBehavior: { desktop: 'row', tablet: 'row', mobile: 'row' },
    accessibilityRequirements: ['icon is aria-hidden reinforcement; actor name + action text carry the meaning'],
    rtlBehavior: 'Icon+text gap logical.',
    darkModeBehavior: 'bg.ai-subtle (AI actor) / bg.sunken (human/system) tokens.',
    status: 'ready',
    filePath: 'components/tbos/activity/ActivityItem.tsx',
  },
  {
    componentId: 'TBOS-CMP-ACTIVITY-002',
    name: 'ActivityTimeline',
    level: 'tbos',
    category: 'activity',
    description: 'The Price/Status History Timeline anatomy — real <ol>, newest-first.',
    sourceDocuments: ['design-system/12_COMPONENT_GUIDELINES.md §2'],
    screenIds: ['PROP-02', 'LEAD-03', 'CONT-02', 'CUST-02'],
    states: ['empty', 'populated'],
    responsiveBehavior: { desktop: 'vertical list', tablet: 'vertical list', mobile: 'vertical list' },
    accessibilityRequirements: ['semantically ordered list, each entry independently focusable via its ActivityItem content'],
    rtlBehavior: 'border-s vertical line (logical) — sits on the correct edge in RTL automatically.',
    darkModeBehavior: 'border token.',
    status: 'ready',
    filePath: 'components/tbos/activity/ActivityTimeline.tsx',
  },
  {
    componentId: 'TBOS-CMP-FEEDBACK-002',
    name: 'RestrictedState',
    level: 'tbos',
    category: 'feedback',
    description: 'Payment-required/subscription-expired universal state — states the specific restriction and number/date, never vague.',
    sourceDocuments: ['tbos-blueprint/06_STATE_ARCHITECTURE.md §1 Restricted'],
    screenIds: ['WAL-01', 'WAL-02'],
    states: [],
    responsiveBehavior: { desktop: 'centered block', tablet: 'centered block', mobile: 'centered block' },
    accessibilityRequirements: ['role="alert"'],
    rtlBehavior: 'Centered content, logical text alignment.',
    darkModeBehavior: 'bg.warning-subtle/text.warning tokens.',
    status: 'ready',
    filePath: 'components/feedback/RestrictedState.tsx',
  },
  {
    componentId: 'TBOS-CMP-FEEDBACK-003',
    name: 'OfflineState',
    level: 'tbos',
    category: 'feedback',
    description: 'Offline universal state — always carries the as-of timestamp of the data shown underneath it.',
    sourceDocuments: ['tbos-blueprint/06_STATE_ARCHITECTURE.md §1 Offline'],
    screenIds: [],
    states: [],
    responsiveBehavior: { desktop: 'banner row', tablet: 'banner row', mobile: 'banner row, may wrap' },
    accessibilityRequirements: ['role="status"'],
    rtlBehavior: 'Icon+text logical; retry button at logical end.',
    darkModeBehavior: 'bg.sunken token.',
    status: 'ready',
    filePath: 'components/feedback/OfflineState.tsx',
  },

  // ============================================================
  // LEVEL 3 — PRODUCT PATTERNS
  // ============================================================
  {
    componentId: 'TBOS-PAT-DATA-001',
    name: 'DataTable',
    level: 'pattern',
    category: 'data',
    description: 'The Record List / Data Table — real <table>/<th scope>, selection, sortable columns, loading/error/empty states. Never sorts/filters data itself.',
    sourceDocuments: ['design-system/12_COMPONENT_GUIDELINES.md §2 Record List + Data Table'],
    screenIds: ['PROP-01', 'PROJ-01', 'LEAD-02', 'CUST-01', 'OWN-01', 'CONT-01', 'MKT-01', 'TASK-01', 'AUTO-01', 'RPT-01', 'FIN-01', 'PC-01', 'PC-02'],
    states: ['loading', 'error', 'empty', 'success'],
    responsiveBehavior: { desktop: 'full table', tablet: 'full table', mobile: 'horizontal scroll (master prompt §13 sanctions this as a valid mobile strategy)' },
    accessibilityRequirements: ['<th scope="col">', 'aria-sort on sortable headers', 'checkbox column has a real accessible label per row'],
    rtlBehavior: 'Numeric columns align to the logical end edge (text-end), never physical "right".',
    darkModeBehavior: 'bg.sunken header row, border tokens throughout.',
    status: 'ready',
    filePath: 'components/patterns/data-table/DataTable.tsx',
  },
  {
    componentId: 'TBOS-PAT-DATA-002',
    name: 'Pagination',
    level: 'pattern',
    category: 'data',
    description: 'Consumes the same Pagination shape lib/api already returns — no adapter needed for a real paginated backend.',
    sourceDocuments: ['master prompt §37'],
    screenIds: ['PROP-01', 'LEAD-02', 'CUST-01', 'OWN-01', 'CONT-01'],
    states: [],
    responsiveBehavior: { desktop: 'row', tablet: 'row', mobile: 'row' },
    accessibilityRequirements: ['nav aria-label="Pagination"', 'Previous/Next disabled state is real button disabled, not visual-only'],
    rtlBehavior: 'Previous/Next order follows logical flex order (no manual swap needed).',
    darkModeBehavior: 'inherits Button.',
    status: 'ready',
    filePath: 'components/patterns/data-table/Pagination.tsx',
  },
  {
    componentId: 'TBOS-PAT-DATA-003',
    name: 'DataTableToolbar',
    level: 'pattern',
    category: 'data',
    description: 'FilterBar + trailing actions slot above a DataTable.',
    sourceDocuments: ['master prompt §37'],
    screenIds: ['PROP-01', 'LEAD-02', 'CUST-01', 'OWN-01', 'CONT-01', 'MKT-01'],
    states: [],
    responsiveBehavior: { desktop: 'row (filters left, actions right)', tablet: 'row', mobile: 'stacked (filters above actions)' },
    accessibilityRequirements: ['inherits FilterBar'],
    rtlBehavior: 'inherits FilterBar; actions at logical end.',
    darkModeBehavior: 'inherits FilterBar.',
    status: 'ready',
    filePath: 'components/patterns/data-table/DataTableToolbar.tsx',
  },
  {
    componentId: 'TBOS-PAT-DATA-004',
    name: 'KanbanBoard',
    level: 'pattern',
    category: 'data',
    description: "LEAD-01's stage view — columns as lifecycle stages, keyboard-operable stage-move as the mandatory alternative to drag.",
    sourceDocuments: ['design-system/12_COMPONENT_GUIDELINES.md §2 Kanban Board'],
    screenIds: ['LEAD-01'],
    states: ['empty_column', 'populated'],
    responsiveBehavior: { desktop: 'horizontal columns', tablet: 'horizontal columns, scrollable', mobile: 'horizontal scroll (a mobile-native single-column view is deferred, see report)' },
    accessibilityRequirements: ['every card has a real "move to stage" menu — drag is never the only mechanism (binding rule)'],
    rtlBehavior: 'Column order follows document flow (flex row reverses automatically under dir=rtl) — "stage progression reads start-to-end" per design-system/15_INTERNATIONALIZATION.md §2.',
    darkModeBehavior: 'bg.sunken column background, bg.surface card tokens.',
    status: 'ready',
    filePath: 'components/patterns/kanban/KanbanBoard.tsx',
  },
  {
    componentId: 'TBOS-CMP-DATA-004',
    name: 'KanbanCard',
    level: 'tbos',
    category: 'data',
    description: 'One Kanban card — content slot + keyboard-operable move-to-stage menu.',
    sourceDocuments: ['design-system/12_COMPONENT_GUIDELINES.md §2 Kanban Board accessibility rule'],
    screenIds: ['LEAD-01'],
    states: [],
    responsiveBehavior: { desktop: 'fixed-width card in column', tablet: 'fixed-width card', mobile: 'fixed-width card' },
    accessibilityRequirements: ['move-to-stage Dropdown is a real, focus-trapped menu, never drag-only'],
    rtlBehavior: 'Menu trigger at logical end of card header.',
    darkModeBehavior: 'bg.surface/shadow-1 tokens.',
    status: 'ready',
    filePath: 'components/patterns/kanban/KanbanCard.tsx',
  },
  {
    componentId: 'TBOS-PAT-FILTER-001',
    name: 'FilterChip',
    level: 'pattern',
    category: 'filter',
    description: 'One removable active-filter chip.',
    sourceDocuments: ['design-system/12_COMPONENT_GUIDELINES.md §3'],
    screenIds: [],
    states: [],
    responsiveBehavior: { desktop: 'inline', tablet: 'inline', mobile: 'inline, wraps' },
    accessibilityRequirements: ['remove button has a descriptive aria-label naming the specific filter'],
    rtlBehavior: 'Remove button at logical end (pe-1.5).',
    darkModeBehavior: 'bg.brand-subtle/text.brand tokens.',
    status: 'ready',
    filePath: 'components/patterns/filters/FilterChip.tsx',
  },
  {
    componentId: 'TBOS-PAT-FILTER-002',
    name: 'FilterBar',
    level: 'pattern',
    category: 'filter',
    description: 'Search input + removable filter chips + sort control slot. Chart filters reuse this exact component.',
    sourceDocuments: ['design-system/12_COMPONENT_GUIDELINES.md §3', 'design-system/13_DATA_VISUALIZATION.md §6'],
    screenIds: ['PROP-01', 'PROJ-01', 'LEAD-01', 'LEAD-02', 'CUST-01', 'OWN-01', 'CONT-01', 'ANL-01', 'RPT-01'],
    states: ['default', 'filters-active'],
    responsiveBehavior: { desktop: 'inline row', tablet: 'inline row', mobile: 'stacked, filter chips wrap' },
    accessibilityRequirements: ['search input has aria-label', 'active-filter count announced via aria-live'],
    rtlBehavior: 'Search icon at logical start (ps-9); text-start placeholder.',
    darkModeBehavior: 'bg.surface/border tokens.',
    status: 'ready',
    filePath: 'components/patterns/filters/FilterBar.tsx',
  },
  {
    componentId: 'TBOS-PAT-LAYOUT-001',
    name: 'PageHeader',
    level: 'pattern',
    category: 'layout',
    description: 'The list-type-screen page header (title + subtitle + actions) — extracted from 4 hand-duplicated copies during the Product UI Consistency Audit (TBOS_PRODUCT_UI_CONSISTENCY_AUDIT.md).',
    sourceDocuments: ['TBOS_PRODUCT_UI_CONSISTENCY_AUDIT.md'],
    screenIds: ['TODAY-01', 'LEAD-01', 'LEAD-02', 'NOTIF-01', 'PROP-01'],
    states: [],
    responsiveBehavior: { desktop: 'row, actions at logical end', tablet: 'row', mobile: 'wraps — title block above actions when both present' },
    accessibilityRequirements: ['real <h1>, one per page'],
    rtlBehavior: 'justify-between is logical; title block and actions swap sides automatically under dir=rtl.',
    darkModeBehavior: 'text.primary/text.secondary tokens; no own background.',
    status: 'ready',
    filePath: 'components/patterns/layout/PageHeader.tsx',
  },
  {
    componentId: 'TBOS-PAT-ENTITY-001',
    name: 'EntityDetailHeader',
    level: 'pattern',
    category: 'entity',
    description: 'The Detail Header anatomy for every *-02 screen — title (h1) + status + primary/secondary actions.',
    sourceDocuments: ['design-system/12_COMPONENT_GUIDELINES.md §2 Detail Header'],
    screenIds: ['PROP-02', 'PROJ-02', 'LEAD-03', 'CUST-02', 'OWN-02', 'CONT-02', 'MKT-02', 'RPT-02', 'WAL-02'],
    states: [],
    responsiveBehavior: { desktop: 'row (title left, actions right)', tablet: 'row', mobile: 'stacked (title above actions); primary action never collapses into overflow, only secondary actions would (caller composes that via Dropdown — not automatic yet, see report)' },
    accessibilityRequirements: ['real <h1>', 'status badge adjacent to title, not detached'],
    rtlBehavior: 'tablet:justify-between is logical; title block and actions swap sides automatically under dir=rtl.',
    darkModeBehavior: 'border-b token; no own background.',
    status: 'ready',
    filePath: 'components/patterns/entity-detail/EntityDetailHeader.tsx',
  },
  {
    componentId: 'TBOS-PAT-FEEDBACK-001',
    name: 'ConfirmationDialog',
    level: 'pattern',
    category: 'feedback',
    description: 'Standard or destructive (alertdialog) confirm-before-proceeding — states the specific, scoped consequence.',
    sourceDocuments: ['design-system/12_COMPONENT_GUIDELINES.md §4', 'tbos-blueprint/17_ACCEPTANCE_CRITERIA.md WF-DELETION'],
    screenIds: [],
    states: ['standard', 'destructive'],
    responsiveBehavior: { desktop: 'centered modal', tablet: 'centered modal', mobile: 'centered modal with padding' },
    accessibilityRequirements: ['role=alertdialog for destructive variant', 'inherits Dialog'],
    rtlBehavior: 'inherits Dialog; Cancel/Confirm button order follows logical flex.',
    darkModeBehavior: 'inherits Dialog.',
    status: 'ready',
    filePath: 'components/patterns/feedback/ConfirmationDialog.tsx',
  },
  {
    componentId: 'TBOS-PAT-FEEDBACK-002',
    name: 'BulkActionBar',
    level: 'pattern',
    category: 'feedback',
    description: 'Appears only when ≥1 row is selected; states count + available bulk actions.',
    sourceDocuments: ['design-system/12_COMPONENT_GUIDELINES.md §3 Bulk Action Bar'],
    screenIds: ['PROP-01', 'LEAD-01', 'LEAD-02', 'CUST-01', 'CONT-01', 'TASK-01'],
    states: ['hidden', 'visible'],
    responsiveBehavior: { desktop: 'sticky top row', tablet: 'sticky top row', mobile: 'sticky top row, may wrap' },
    accessibilityRequirements: ['selection count in aria-live region'],
    rtlBehavior: 'Actions + Clear button follow logical flex order.',
    darkModeBehavior: 'bg.brand-strong/text.on-brand tokens.',
    status: 'ready',
    filePath: 'components/patterns/feedback/BulkActionBar.tsx',
  },
  {
    componentId: 'TBOS-PAT-FORM-001',
    name: 'StepIndicator',
    level: 'pattern',
    category: 'form',
    description: 'Replaces a breadcrumb on Wizard flows — "Step 2 of 4: Compliance."',
    sourceDocuments: ['design-system/12_COMPONENT_GUIDELINES.md §3', 'tbos-blueprint/02_NAVIGATION_BLUEPRINT.md §9'],
    screenIds: ['PROP-03', 'PROJ-03', 'ONB-01'],
    states: [],
    responsiveBehavior: { desktop: 'horizontal row', tablet: 'horizontal row', mobile: 'horizontal row, may need horizontal scroll for >4 steps (deferred enhancement)' },
    accessibilityRequirements: ['aria-current="step" on the active step', 'aria-label states "Step N of M"'],
    rtlBehavior: 'Connector lines and step order follow document flow (flex row reverses automatically).',
    darkModeBehavior: 'bg.brand (complete) / border-brand (current) / bg.sunken (upcoming) tokens.',
    status: 'ready',
    filePath: 'components/patterns/forms/StepIndicator.tsx',
  },
  {
    componentId: 'TBOS-PAT-FORM-002',
    name: 'FormWizard',
    level: 'pattern',
    category: 'form',
    description: 'StepIndicator + step body + back/next/submit — front-loaded requirements (Next disabled until the step is valid).',
    sourceDocuments: ['design-system/12_COMPONENT_GUIDELINES.md §3 Wizard/Stepper'],
    screenIds: ['PROP-03', 'PROJ-03', 'ONB-01'],
    states: ['saving'],
    responsiveBehavior: { desktop: 'centered content, 8 of 12 cols per design-system/06_GRID_SYSTEM.md §3', tablet: '6 of 8 cols', mobile: 'full width' },
    accessibilityRequirements: ['inherits StepIndicator', 'Back/Next/Submit are real buttons with disabled state, not silent no-ops'],
    rtlBehavior: 'Back/Next row uses justify-between (logical).',
    darkModeBehavior: 'inherits Button/StepIndicator.',
    status: 'ready',
    filePath: 'components/patterns/forms/FormWizard.tsx',
  },
  {
    componentId: 'TBOS-PAT-FORM-003',
    name: 'MediaUploader',
    level: 'pattern',
    category: 'form',
    description: 'The File/Media Uploader pattern — per-file uploading/processing/approved/rejected status, retry affordance on failure.',
    sourceDocuments: ['tbos-blueprint/05_COMPONENT_MAPPING.md', 'tbos-blueprint/17_ACCEPTANCE_CRITERIA.md "Media upload fails mid-flow"'],
    screenIds: ['PROP-03', 'PROJ-03'],
    states: ['uploading', 'processing', 'approved', 'rejected'],
    responsiveBehavior: { desktop: 'full width of container', tablet: 'full width', mobile: 'full width, file list stacks' },
    accessibilityRequirements: ['real <input type="file">, never a fake drop zone with no keyboard path', 'each file row states its own status as text, not color alone'],
    rtlBehavior: 'File name truncates from the logical end; status/retry controls follow logical flex order.',
    darkModeBehavior: 'border.default/bg.sunken/text.danger tokens.',
    status: 'ready',
    filePath: 'components/patterns/forms/MediaUploader.tsx',
  },
  {
    componentId: 'TBOS-PAT-SEARCH-001',
    name: 'SearchResultGroup',
    level: 'pattern',
    category: 'search',
    description: 'A labeled group of results by entity category, for a future full-page GS-01 results screen.',
    sourceDocuments: ['tbos-blueprint/10_SEARCH_EXPERIENCE.md §1'],
    screenIds: ['GS-01'],
    states: [],
    responsiveBehavior: { desktop: 'grouped list', tablet: 'grouped list', mobile: 'grouped list' },
    accessibilityRequirements: ['real <h2> group heading', 'real <ul>/<li> results list'],
    rtlBehavior: 'text-start title/subtitle.',
    darkModeBehavior: 'text.muted heading token.',
    status: 'ready',
    filePath: 'components/patterns/search/SearchResultGroup.tsx',
  },
  {
    componentId: 'TBOS-PAT-SEARCH-002',
    name: 'SearchEmptyState',
    level: 'pattern',
    category: 'search',
    description: 'Zero-result state requiring a broadening suggestion or creation CTA — a bare "no results" never ships.',
    sourceDocuments: ['tbos-blueprint/10_SEARCH_EXPERIENCE.md §15'],
    screenIds: ['GS-01'],
    states: [],
    responsiveBehavior: { desktop: 'centered block', tablet: 'centered block', mobile: 'centered block' },
    accessibilityRequirements: ['suggestion is a required prop — cannot render a bare "no results" by construction'],
    rtlBehavior: 'Centered content.',
    darkModeBehavior: 'icon.muted token.',
    status: 'ready',
    filePath: 'components/patterns/search/SearchEmptyState.tsx',
  },
  {
    componentId: 'TBOS-PAT-SEARCH-003',
    name: 'CommandPalette',
    level: 'pattern',
    category: 'search',
    description: 'GS-01 + CMD-01\'s combined surface — plain query = search, `>` prefix = commands. Built in the Foundation phase; registered here for traceability, not re-implemented.',
    sourceDocuments: ['tbos-blueprint/02_NAVIGATION_BLUEPRINT.md §8', 'tbos-blueprint/10_SEARCH_EXPERIENCE.md §6'],
    screenIds: ['GS-01', 'CMD-01'],
    states: ['search_mode', 'command_mode', 'empty', 'results'],
    responsiveBehavior: { desktop: 'centered overlay', tablet: 'centered overlay', mobile: 'centered overlay, full-width' },
    accessibilityRequirements: ['focus-trapped', 'aria-live announces result count'],
    rtlBehavior: 'Mode icon at logical start; results text-start.',
    darkModeBehavior: 'bg.surface/border tokens.',
    status: 'ready',
    filePath: 'components/navigation/CommandPalette.tsx',
  },
  {
    componentId: 'TBOS-PAT-ACTION-001',
    name: 'QuickActionsPanel',
    level: 'pattern',
    category: 'action',
    description: 'QA-01 — the top-4 JTBD-ranked actions, permission-filtered, never a disabled 4th. Built in the Foundation phase; registered here for traceability.',
    sourceDocuments: ['tbos-definition/08_NAVIGATION_SYSTEM.md'],
    screenIds: ['QA-01'],
    states: [],
    permissions: ['leads.view', 'properties.create', 'tasks.create', 'settings.compliance.manage'],
    responsiveBehavior: { desktop: 'centered modal grid', tablet: 'centered modal grid', mobile: 'bottom sheet' },
    accessibilityRequirements: ['focus-trapped', 'each action is a real button with a descriptive name'],
    rtlBehavior: 'Grid order follows document flow.',
    darkModeBehavior: 'bg.surface tokens.',
    status: 'ready',
    filePath: 'components/navigation/QuickActionsPanel.tsx',
  },

  // ============================================================
  // LEVEL 4 — SHELL / NAVIGATION (built in the Foundation phase, registered here for traceability)
  // ============================================================
  {
    componentId: 'TBOS-SHL-NAV-001',
    name: 'RailNav',
    level: 'shell',
    category: 'navigation',
    description: 'Broker OS three-group collapsible left rail — RBAC- and feature-flag-filtered from the module/screen registries.',
    sourceDocuments: ['tbos-blueprint/02_NAVIGATION_BLUEPRINT.md §1'],
    screenIds: [],
    states: ['expanded', 'collapsed'],
    responsiveBehavior: { desktop: 'persistent, 240px expanded/64px collapsed', tablet: 'icon-only by default', mobile: 'hidden (MobileTabBar takes over)' },
    accessibilityRequirements: ['aria-current="page" on active item; RBAC-hidden items are absent, never disabled'],
    rtlBehavior: 'border-e (logical); collapse chevron rtl:rotate-180.',
    darkModeBehavior: 'bg.surface/border-e tokens.',
    status: 'ready',
    filePath: 'layouts/AppShell/RailNav.tsx',
  },
  {
    componentId: 'TBOS-SHL-NAV-002',
    name: 'TopBar',
    level: 'shell',
    category: 'navigation',
    description: 'Search entry, Quick Actions, Notifications, theme/locale toggles, account menu.',
    sourceDocuments: ['tbos-blueprint/02_NAVIGATION_BLUEPRINT.md §1'],
    screenIds: [],
    states: [],
    responsiveBehavior: { desktop: 'full row', tablet: 'full row', mobile: 'full row, Quick Actions button hidden (mobile tab bar has its own)' },
    accessibilityRequirements: ['persistent search field, never a reveal-on-click button'],
    rtlBehavior: 'Search icon at logical start; kbd hint at logical end (ms-auto).',
    darkModeBehavior: 'bg.surface/border-b tokens.',
    status: 'ready',
    filePath: 'layouts/AppShell/TopBar.tsx',
  },
  {
    componentId: 'TBOS-SHL-NAV-003',
    name: 'MobileTabBar',
    level: 'shell',
    category: 'navigation',
    description: 'Exactly 5 fixed destinations — Home, Today, Search, Quick Actions (elevated center), Notifications. Never expands to the full desktop tree.',
    sourceDocuments: ['tbos-blueprint/02_NAVIGATION_BLUEPRINT.md §3'],
    screenIds: [],
    states: ['active', 'default'],
    responsiveBehavior: { desktop: 'hidden', tablet: 'hidden', mobile: 'fixed bottom bar' },
    accessibilityRequirements: ['each tab is a real link/button with a text label, not icon-only'],
    rtlBehavior: 'Tab order mirrors via flex row reversal under dir=rtl.',
    darkModeBehavior: 'bg.surface/border-t tokens.',
    status: 'ready',
    filePath: 'layouts/AppShell/MobileTabBar.tsx',
  },
  {
    componentId: 'TBOS-SHL-NAV-004',
    name: 'UserMenu',
    level: 'shell',
    category: 'navigation',
    description: 'Account/persona switcher — only offers role-switching when the user holds more than one role.',
    sourceDocuments: ['tbos-blueprint/02_NAVIGATION_BLUEPRINT.md §1'],
    screenIds: [],
    states: [],
    responsiveBehavior: { desktop: 'dropdown', tablet: 'dropdown', mobile: 'dropdown' },
    accessibilityRequirements: ['role=menu/menuitemradio for role options', 'focus-trapped'],
    rtlBehavior: 'Dropdown anchors to logical end (end-0).',
    darkModeBehavior: 'bg.surface/border tokens.',
    status: 'ready',
    filePath: 'layouts/AppShell/UserMenu.tsx',
  },
  {
    componentId: 'TBOS-SHL-LAYOUT-001',
    name: 'AppShell',
    level: 'shell',
    category: 'layout',
    description: 'The Broker OS application shell — composes RailNav + TopBar + MobileTabBar + overlays.',
    sourceDocuments: ['ARCHITECTURE.md'],
    screenIds: [],
    states: [],
    responsiveBehavior: { desktop: 'rail + top bar', tablet: 'collapsed rail + top bar', mobile: 'top bar + bottom tab bar' },
    accessibilityRequirements: ['route change moves focus to the new screen\'s primary heading (deferred — see report)'],
    rtlBehavior: 'flex-row-reverse-safe via logical flex composition throughout.',
    darkModeBehavior: 'bg.canvas token on <main>.',
    status: 'ready',
    filePath: 'layouts/AppShell/AppShell.tsx',
  },
  {
    componentId: 'TBOS-SHL-NAV-005',
    name: 'ConsoleNav',
    level: 'shell',
    category: 'navigation',
    description: 'Platform Console\'s own flat nav list — architecturally separate from RailNav, shares zero chrome components with it.',
    sourceDocuments: ['tbos-definition/00_PRODUCT_CONSTITUTION.md Article V'],
    screenIds: ['PC-01', 'PC-02', 'PC-03', 'PC-04', 'PC-05'],
    states: [],
    responsiveBehavior: { desktop: 'fixed 288px', tablet: 'fixed 288px', mobile: 'fixed 288px (Console mobile-specific layout deferred, see report)' },
    accessibilityRequirements: ['aria-current="page" on active item'],
    rtlBehavior: 'border-e logical.',
    darkModeBehavior: 'Fixed dark slate chrome regardless of theme (deliberate — visually distinct from Broker OS).',
    status: 'ready',
    filePath: 'layouts/ConsoleShell/ConsoleNav.tsx',
  },
  {
    componentId: 'TBOS-SHL-NAV-006',
    name: 'ConsoleTopBar',
    level: 'shell',
    category: 'navigation',
    description: 'Minimal Console top bar — no Search/Quick Actions/Notifications (none specified for Console this phase).',
    sourceDocuments: ['tbos-blueprint/18_OPEN_QUESTIONS.md Platform Console deferred spec'],
    screenIds: [],
    states: [],
    responsiveBehavior: { desktop: 'row', tablet: 'row', mobile: 'row' },
    accessibilityRequirements: ['inherits IconButton'],
    rtlBehavior: 'Actions at logical end.',
    darkModeBehavior: 'Fixed dark slate chrome.',
    status: 'ready',
    filePath: 'layouts/ConsoleShell/ConsoleTopBar.tsx',
  },
  {
    componentId: 'TBOS-SHL-LAYOUT-002',
    name: 'ConsoleShell',
    level: 'shell',
    category: 'layout',
    description: "The Platform Console's application shell — zero shared chrome with AppShell (Constitution Article V).",
    sourceDocuments: ['tbos-definition/00_PRODUCT_CONSTITUTION.md Article V', 'ROUTING.md'],
    screenIds: [],
    states: [],
    responsiveBehavior: { desktop: 'nav + top bar', tablet: 'nav + top bar', mobile: 'nav + top bar (no mobile-specific Console layout yet, see report)' },
    accessibilityRequirements: ['inherits ConsoleNav/ConsoleTopBar'],
    rtlBehavior: 'inherits ConsoleNav/ConsoleTopBar.',
    darkModeBehavior: 'Fixed dark chrome, bg.canvas content area.',
    status: 'ready',
    filePath: 'layouts/ConsoleShell/ConsoleShell.tsx',
  },
  {
    componentId: 'TBOS-SHL-LAYOUT-003',
    name: 'AuthLayout',
    level: 'shell',
    category: 'layout',
    description: 'Broker OS mock sign-in — persona picker excluding platform roles.',
    sourceDocuments: ['RBAC.md', 'ROUTING.md'],
    screenIds: [],
    states: ['loading', 'error'],
    responsiveBehavior: { desktop: 'centered card', tablet: 'centered card', mobile: 'centered card, full-width' },
    accessibilityRequirements: ['each persona is a real button'],
    rtlBehavior: 'text-center content, direction-agnostic.',
    darkModeBehavior: 'bg.canvas/bg.surface tokens.',
    status: 'ready',
    filePath: 'layouts/AuthLayout/AuthLayout.tsx',
  },
  {
    componentId: 'TBOS-SHL-LAYOUT-004',
    name: 'ConsoleAuthLayout',
    level: 'shell',
    category: 'layout',
    description: 'Platform Console\'s own, separate sign-in surface — visually distinct dark chrome, lists only platform personas.',
    sourceDocuments: ['tbos-definition/00_PRODUCT_CONSTITUTION.md Article V'],
    screenIds: [],
    states: ['loading', 'error'],
    responsiveBehavior: { desktop: 'centered card', tablet: 'centered card', mobile: 'centered card, full-width' },
    accessibilityRequirements: ['each persona is a real button'],
    rtlBehavior: 'text-center content.',
    darkModeBehavior: 'Fixed dark chrome regardless of theme (deliberate).',
    status: 'ready',
    filePath: 'layouts/ConsoleAuthLayout/ConsoleAuthLayout.tsx',
  },
  {
    componentId: 'TBOS-SHL-LAYOUT-005',
    name: 'FullscreenLayout',
    level: 'shell',
    category: 'layout',
    description: 'No-chrome layout for full-bleed surfaces (404, onboarding).',
    sourceDocuments: ['ARCHITECTURE.md'],
    screenIds: ['ONB-01'],
    states: [],
    responsiveBehavior: { desktop: 'full viewport', tablet: 'full viewport', mobile: 'full viewport' },
    accessibilityRequirements: [],
    rtlBehavior: 'No chrome to mirror.',
    darkModeBehavior: 'bg.canvas token.',
    status: 'ready',
    filePath: 'layouts/FullscreenLayout/FullscreenLayout.tsx',
  },
];

export const COMPONENT_MAP: Record<string, ComponentRegistryEntry> = Object.fromEntries(COMPONENT_REGISTRY.map((c) => [c.componentId, c]));
