import type { RolePermissionMap } from '@/types/rbac';

/**
 * Role → permission grants, derived directly from the Primary user / Permissions
 * fields of every screen in tbos-blueprint/04_SCREEN_INVENTORY.md. This is a
 * frontend UX layer only (design-system's binding rule, see RBAC.md) — the
 * authoritative grant always comes from the backend once one exists; this map is
 * what lets the foundation demonstrate scoped navigation/route-guarding today.
 *
 * grant() is a local helper purely to keep this table legible; it has no behavior
 * beyond object-shaping.
 */
const grant = (permission: string, scope: 'own' | 'team' | 'agency' | 'platform') => ({ permission, scope });

const BASE_FOR_ALL_BROKER_ROLES = [
  grant('home.view', 'own'),
  grant('today.view', 'own'),
  grant('today.act', 'own'),
  grant('tasks.view', 'own'),
  grant('tasks.create', 'own'),
  grant('notifications.view', 'own'),
  grant('knowledge.view', 'own'),
  grant('settings.profile.edit', 'own'),
  grant('wallet.view', 'own'),
  grant('ai_copilot.view', 'own'),
  grant('ai_audit.view', 'own'),
];

export const ROLE_PERMISSIONS: RolePermissionMap = {
  SB: [
    ...BASE_FOR_ALL_BROKER_ROLES,
    grant('properties.view', 'own'),
    grant('properties.create', 'own'),
    grant('properties.edit', 'own'),
    grant('properties.delete', 'own'),
    grant('properties.compliance.edit', 'own'),
    grant('projects.view', 'own'),
    grant('projects.create', 'own'),
    grant('projects.edit', 'own'),
    grant('leads.view', 'own'),
    grant('leads.assign', 'own'),
    grant('leads.respond', 'own'),
    grant('customers.view', 'own'),
    grant('customers.edit', 'own'),
    grant('owners.view', 'own'),
    grant('owners.edit', 'own'),
    grant('marketing_requests.view', 'own'),
    grant('marketing_requests.respond', 'own'),
    grant('contracts.view', 'own'),
    grant('marketing.view', 'own'),
    grant('marketing.manage', 'own'),
    grant('wallet.manage', 'own'),
    grant('analytics.view', 'own'),
    grant('settings.compliance.view', 'own'),
    grant('settings.compliance.manage.own', 'own'),
  ],
  AO: [
    ...BASE_FOR_ALL_BROKER_ROLES,
    grant('tasks.view.team', 'agency'),
    grant('tasks.assign', 'agency'),
    grant('properties.view', 'agency'),
    grant('properties.create', 'agency'),
    grant('properties.edit', 'agency'),
    grant('properties.delete', 'agency'),
    grant('properties.compliance.edit', 'agency'),
    grant('projects.view', 'agency'),
    grant('projects.create', 'agency'),
    grant('projects.edit', 'agency'),
    grant('leads.view', 'agency'),
    grant('leads.view.team', 'agency'),
    grant('leads.assign', 'agency'),
    grant('leads.respond', 'agency'),
    grant('leads.export', 'agency'),
    grant('customers.view', 'agency'),
    grant('customers.edit', 'agency'),
    grant('owners.view', 'agency'),
    grant('owners.edit', 'agency'),
    grant('marketing_requests.view', 'agency'),
    grant('marketing_requests.respond', 'agency'),
    grant('contracts.view', 'agency'),
    grant('contracts.approve', 'agency'),
    grant('marketing.view', 'agency'),
    grant('marketing.manage', 'agency'),
    grant('finance.view', 'agency'),
    grant('wallet.view.agency', 'agency'),
    grant('wallet.manage', 'agency'),
    grant('analytics.view', 'agency'),
    grant('reports.view', 'agency'),
    grant('automation.view', 'agency'),
    grant('automation.manage', 'agency'),
    grant('ai_audit.view.agency', 'agency'),
    grant('settings.roles.manage', 'agency'),
    grant('settings.integrations.manage', 'agency'),
    grant('settings.compliance.view', 'agency'),
    grant('settings.compliance.manage', 'agency'),
  ],
  SM: [
    ...BASE_FOR_ALL_BROKER_ROLES,
    grant('tasks.view.team', 'team'),
    grant('tasks.assign', 'team'),
    grant('leads.view', 'team'),
    grant('leads.view.team', 'team'),
    grant('leads.assign', 'team'),
    grant('leads.respond', 'team'),
    grant('leads.export', 'team'),
    grant('automation.view', 'team'),
    grant('automation.manage', 'team'),
    grant('analytics.view', 'team'),
  ],
  MM: [
    ...BASE_FOR_ALL_BROKER_ROLES,
    grant('properties.view', 'agency'),
    grant('properties.edit', 'agency'),
    grant('projects.view', 'agency'),
    grant('projects.edit', 'agency'),
    grant('owners.view', 'agency'),
    grant('owners.edit', 'agency'),
    grant('marketing_requests.view', 'agency'),
    grant('marketing_requests.respond', 'agency'),
    grant('marketing.view', 'agency'),
    grant('marketing.manage', 'agency'),
    grant('analytics.view', 'agency'),
  ],
  OM: [
    ...BASE_FOR_ALL_BROKER_ROLES,
    grant('properties.view', 'agency'),
    grant('properties.compliance.edit', 'agency'),
    grant('projects.view', 'agency'),
    grant('contracts.view', 'agency'),
    grant('contracts.approve', 'agency'),
    grant('finance.view', 'agency'),
    grant('reports.view', 'agency'),
    grant('automation.view', 'agency'),
    grant('automation.manage', 'agency'),
    grant('analytics.view', 'agency'),
    grant('ai_audit.view.agency', 'agency'),
    grant('settings.integrations.manage', 'agency'),
    grant('settings.compliance.view', 'agency'),
    grant('settings.compliance.manage', 'agency'),
  ],
  PC: [
    ...BASE_FOR_ALL_BROKER_ROLES,
    grant('properties.view', 'own'),
    grant('properties.create', 'own'),
    grant('properties.edit', 'own'),
    grant('projects.view', 'own'),
    grant('leads.view', 'own'),
    grant('leads.respond', 'own'),
    grant('customers.view', 'own'),
    grant('customers.edit', 'own'),
    grant('owners.view', 'own'),
    grant('marketing_requests.view', 'own'),
    grant('marketing_requests.respond', 'own'),
    grant('contracts.view', 'own'),
    grant('analytics.view', 'own'),
  ],
  ADM: [grant('platform_console.access', 'platform')],
};
